---
- name: restart docker
  become: true
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  when:
    - ansible_os_family not in ('Windows', 'Darwin')

- name: reload systemd daemon
  become: true
  systemd:
    daemon_reload: true
  when:
    - ansible_os_family not in ('Windows', 'Darwin')

- name: restart containerd
  become: true
  systemd:
    name: containerd
    state: restarted
