---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure sudo priviledges
  become: true
  block:
    - include_tasks: sudo.yml
  when: ansible_os_family != 'Windows'

- name: Configure autoupdating
  become: true
  block:
    - include_tasks: "autoupdate-{{ ansible_os_family }}.yml"
  when: security_autoupdate_enabled | bool
