---
- name: "Ensure {{ app_name }} is installed"
  become: false
  become_user: "{{ ansible_user }}"
  community.general.homebrew:
    name: rclone
    state: present

- name: Run generic Darwin tasks
  include_tasks: user-Darwin.yml
