---
- name: "Ensure {{ app_name }} is installed"
  become: false
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ win_packages }}"
    state: latest

- name: Run generic user tasks
  include_tasks: user-Windows.yml
