---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures rclone is installed
# Installs rclone on Archlinux, CentOS, Debian, Fedora, Ubuntu, MacOS and Windows
# @action Ensures rclone is configured
# Creates rclone configuration file containing settings for the configured providers
# @action Ensures rclone is configured
# Creates directories for use as mount points to mount remote
# @action Ensures rclone is configured
# Sets up rclone mount services
# @action Ensures rclone is configured
# Starts rclone mount services
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
