---
- name: Add youtube-dl apt repository
  apt_repository:
    filename: youtubedl
    repo: "{{ youtube_dl_apt_repository }}"
    state: present
    update_cache: yes

- name: Ensure youtube-dl is installed
  apt:
    name: youtube-dl
    state: present
