---
ansible_become_method: runas # TODO: Move all these ansible variables to the ansible.cfg
ansible_become_pass: "{{ admin_password }}"

ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: credssp
ansible_winrm_operation_timeout_sec: 1200
ansible_winrm_read_timeout_sec: 1800
