- name: uninstall old docker versions
  apt:
    name: "{{ absent_packages }}"
    state: absent 

- name: install required packages 
  apt:
    name: "{{ required_packages }}"
    state: latest

- name: Add docker GPG key for ubuntu
  apt_key:
    url: "{{ docker_ubuntu_gpg }}"

- name: Add docker apt repository 
  apt_repository:
    repo: "{{ docker_ubuntu_repo }}"

- name: Install docker-ce 
  apt:
    name: "{{ docker }}"
    state: latest
  notify: start docker
