---
- name: "Ensure VMware Fusion is installed"
  become: false
  community.general.homebrew_cask:
    name: vmware-fusion
    state: "{{ app_state | default('present') }}"
    sudo_password: "{{ ansible_password }}"
