---
- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: true

- name: Ensure fuse filesystem is installed
  apt:
    name: fuse
    state: present

- name: Ensure snap is started and enabled on boot
  ansible.builtin.systemd:
    enabled: true
    name: snapd
    state: started

- name: Ensure snap core is installed
  community.general.snap:
    name: core
    state: present
