---
- name: Ensure snapd is installed
  yum:
    name: snapd
    state: present
    enablerepo: epel

- name: Enable and start the snapd systemd unit
  systemd:
    name: snapd.socket
    state: started
    enabled: true

- name: Create a link to enable classic snap support
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
