---
- name: Set up Cloudflared DNS over HTTPS
  include_role:
    name: bendews.cloudflared

- name: Copy Cloudflared dnsmasq configuration
  copy:
    dest: /etc/dnsmasq.d/50-cloudflared.conf
    mode: 0600
    src: files/50-cloudflared.conf

- name: Restart pihole-FTL
  service:
    enabled: true
    name: pihole-FTL
    state: restarted
