---
update:common:
  before_script:
    - if [ -n "$UPDATE_INIT_SCRIPT" ]; then curl -s "$UPDATE_INIT_SCRIPT" | bash; fi
    - task ci:before
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/
      - .npm/
      - .pnpm-store/
      - .venv/
  image: megabytelabs/updater:slim
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: ($CI_PIPELINE_SOURCE == 'pipeline' || $CI_PIPELINE_SOURCE == 'web') && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - task start
    - task ci:commit
  stage: update
  variables:
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: recursive
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
