---
- name: "Ensure {{ app_name }} tools are installed"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - helm
    - hyperkit
    - kompose
    - kubectl

- name: "Ensure Minikube is installed"
  community.general.homebrew:
    name: minikube
    state: present
  register: minikube_install

- name: "Ensure Minikube driver is configured" # noqa 503
  command: "minikube config set driver {{ kubernetes_mac_driver }}"
  when: minikube_install.changed
