---
- name: "Ensure {{ app_name }} tools are installed"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
    - kubernetes-cli
    - kubernetes-helm
    - kubernetes-kompose

- name: "Ensure Minikube is installed"
  chocolatey.chocolatey.win_chocolatey:
    name: minikube
    state: present
  register: minikube_install

- name: "Ensure Minikube driver is configured" # noqa 503
  ansible.windows.win_command: "minikube config set driver {{ kubernetes_mac_driver }}"
  when: minikube_install.changed
