---
variables:
  ANSIBLE_CONFIG: ${CI_PROJECT_DIR}/ansible.cfg

stages:
  - update
  - fix
  - lint
  - test

include:
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/ansible-lint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/flake8.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/hadolint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/molecule.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/prettier.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/prettier-fix.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/shellcheck.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/update.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/yamllint.gitlab-ci.yml
