---
- name: "Ensure snapd is installed"
  include_role:
    name: tools/snap

- name: "Ensure rustup is installed"
  community.general.snap:
    name: rustup
    classic: true

- name: "Ensure build-essential is installed"
  apt:
    name: build-essential
    state: present
    update_cache: true

- name: Ensure Megabyte Labs configuration directory exists
  file:
    mode: 0700
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config
    - ~/.config/megabytelabs

- name: "Check if {{ app_name }} has configuration stored in /root/.config/megabytelabs/{{ app_name }}"
  stat:
    path: "~/.config/megabytelabs/{{ app_name }}"
  register: bandwhich_config

- name: "Detect previously installed {{ app_name }} version"
  command: cat bandwhich
  args:
    chdir: ~/.config/megabytelabs
  changed_when: false
  register: current_bandwhich_version
  when: bandwhich_config.stat.exists

- name: "Detect the latest {{ app_name }} version"
  uri:
    url: https://api.github.com/repos/imsnif/bandwhich/releases/latest
  register: bandwhich_latest_release_tag

- name: "Determine whether or not the latest version of {{ app_name }} is already installed"
  set_fact:
    install_bandwhich: "{{ (current_bandwhich_version.skipped) or \
      ((not current_bandwhich_version.skipped) and (current_bandwhich_version.stdout != bandwhich_latest_release_tag.json.tag_name)) }}"

- name: "Ensure older version of {{ app_name }} is uninstalled"
  file:
    path: /usr/local/bin/bandwhich
    state: absent

- name: "Ensure {{ app_name }} is installed"
  shell: |
    rustup install stable
    cargo install bandwhich --root /usr/local
  args:
    creates: /usr/local/bin/bandwhich
  when: install_bandwhich

- name: "Save meta information about the version of {{ app_name }} that was installed"
  copy:
    dest: ~/.config/megabytelabs/bandwhich
    mode: 0600
    content: |
      {{ bandwhich_latest_release_tag.json.tag_name }}
