---
- name: "Ensure {{ app_name }} is installed"
  become: true
  become_user: "{{ homebrew_user }}"
  community.general.homebrew:
    name: bandwhich
    state: "{{ app_state | default('present') }}"
