---
- name: "Ensure {{ app_name }} is installed"
  community.general.snap: # TODO: Accept terms automatically
    classic: true
    name: intellij-idea-community
    state: "{{ app_state | default('present') }}"
