---
wazuh_apt_key_url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
wazuh_apt_repository: "deb {{ https_repository_prefix }}packages.wazuh.com/4.x/apt/ stable main"
wazuh_conf_file: /var/ossec/etc/ossec.conf
