---
- name: "Add {{ app_name }}'s apt key"
  apt_key:
    state: present
    url: "{{ teamviewer_apt_key_url }}"

- name: "Add {{ app_name }}'s apt repository"
  apt_repository:
    filename: "{{ app_name | lower | replace(' ', '') }}"
    repo: "{{ teamviewer_apt_repository }}"
    state: present
    update_cache: true

- name: "Ensure {{ app_name }} is installed"
  apt:
    name: teamviewer
    state: "{{ app_state | default('present') }}"
