- name: Add Teamviewer repo 
  copy:
    src: teamviewer.repo
    dest: "{{ teamviewer_repo_dest }}"

- name: Add signing key 
  rpm_key:
    key: "{{ teamviewer_key }}"

- name: Install Teamviewer
  dnf:
    name: teamviewer
    state: latest 