# https://community.teamviewer.com/t5/Knowledge-Base-EN/How-to-use-the-TAR-package-for-Linux/ta-p/30664
- name: Create teamviewer temp dir 
  file:
    path: "{{ teamviewer_dir }}"
    state: directory

- name: Download teamviewer tarball 
  get_url:
    url: "{{ teamviewer_tarball_url }}"
    dest: "{{ teamviewer_tarball }}"

- name: Extract teamviewer tarball 
  unarchive:
    src: "{{ teamviewer_tarball }}"
    dest: "{{ teamviewer_dir }}"
    remote_src: True 
    extra_opts: [--strip-components=1]

- name: Run Teamviewer installer 
  command: ./tv-setup install force
  args:
    chdir: "{{ teamviewer_dir }}"
  register: test 
