- name: Add Teamviewer repo 
  copy:
    content: deb https://linux.teamviewer.com/deb stable main
    dest: "{{ teamviewer_repo_dest }}" 

- name: Add signing key 
  apt_key:
    url: "{{ teamviewer_key }}"

- name: Install Teamviewer 
  apt:
    name: teamviewer
    state: latest 
    update_cache: True 