---
- name: Add the TeamViewer signing key 
  rpm_key:
    key: "{{ teamviewer_key }}"

- name: Add the TeamViewer repository 
  yum_repository:
    name: teamviewer 
    description: Teamviewer repository
    baseurl: "{{ teamviewer_baseurl }}" 
    gpgcheck: True 
    gpgkey: "{{ teamviewer_key }}"
    repo_gpgcheck: True  
    failovermethod: priority

- name: Install TeamViewer
  dnf:
    name: teamviewer
    state: latest
