---
- name: "Ensure {{ app_name }} is installed"
  unarchive:
    src: "{% if ansible_architecture == 'x86_64' %}{{ ngrok_x86_64_url }} \
      {% elif ('64' in ansible_architecture and ('aarch' in ansible_architecture or 'arm' in ansible_architecture)) %}{{ ngrok_arm64_url }} \
      {% else %}{{ ngrok_arm32_url }}{% endif %}"
    dest: /usr/local/bin
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Ensure authtoken is added to the configuration file
  become_user: "{{ user.username }}"
  block:
    - name: Ensure .ngrok2 folder exists
      file:
        path: "/home/{{ user.username }}/.ngrok2"
        state: directory
        mode: 0750
        owner: "{{ user.username }}"
        group: "{{ user.group }}"
    - name: Ensure authtoken is added to the configuration file
      lineinfile:
        path: "/home/{{ user.username }}/.ngrok2/ngrok.yml"
        regex: "^authtoken"
        line: "authtoken: {{ user.ngrok_token }}"
  when:
    - user.ngrok_token is defined
    - (user.system is not defined) or ((user.system is defined) and (not user.system))
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
