---
# @action Ensures ngrok is installed
# Installs ngrok on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures ngrok is installed
# Ensures ngrok is available on PATH
# @action Ensures ngrok is installed
# Adds Auth token to ngrok's configuration file if provided
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
