---
galaxy_info:
  role_name: mas
  author: ProfessorManhattan and geerlingguy
  description: Installs apps from the Mac OS X app store via CLI
  company: Megabyte Labs
  # issue_tracker_url: http://example.com/issue/tracker
  license: "license (BSD, MIT)"

  min_ansible_version: 2.4

  platforms:
    - name: GenericUNIX
      versions:
        - all
        - any

  galaxy_tags:
    - development
    - system
    - packaging
    - mas
    - mac
    - app
    - store
    - macos

dependencies:
  - professormanhattan.homebrew
