---
software_package:
  altair:
    brew: altair-graphql-client
    choco: altair-graphql
    github: github.com/altair-graphql/altair
    snap: altair
    yay: altair
  askgit:
    brew: askgit
    brew_tap: askgitdev/askgit
    github: github.com/askgitdev/askgit
  bandwhich:
    brew: bandwhich
    cargo: bandwhich
    github: github.com/imsnif/bandwhich
    pacman: bandwhich
    pkg: bandwhich
  bat:
    apk: bat
    brew: bat
    cargo: bat
    choco: bat
    github: bat
    pacman: bat
    scoop: bat
  betwixt:
    github: github.com/kdzwinel/betwixt
  bitwarden:
    brew: bitwarden
    choco: bitwarden
    github: github.com/bitwarden/desktop
    snap: bitwarden
    yay: bitwarden-git
  boilr:
    github: github.com/tmrts/boilr
    go: github.com/tmrts/boilr
  cerebro:
    brew: cerebro
    choco: cerebro
    github: github.com/cerebroapp/cerebro
    yay: cerebro
  clair:
    brew: clair
    github: github.com/quay/clair
  consul-cli:
    github: github.com/mantl/consul-cli
  croc:
    brew: croc
    choco: croc
    github: github.com/schollz/croc
    go: github.com/schollz/croc/v9@latest
    pacman: croc
    pkg: croc
    scoop: croc
  ctop:
    brew: ctop
    github: github.com/bcicen/ctop
    yay: ctop-bin
  cumulus:
    brew: cumulus
    github: github.com/gillesdemey/Cumulus
  dat:
    github: github.com/datproject/dat
    npm: dat@next
  dat-desktop:
    brew: dat
    github: github.com/datproject/dat-desktop
  delta:
    brew: git-delta
    cargo: git-delta
    choco: git-delta
    dnf: git-delta
    github: github.com/dandavison/delta
    pkg: git-delta
    scoop: git-delta
  dive:
    brew: dive
    github: github.com/wagoodman/dive
    go: github.com/wagoodman/dive
    yay: dive
  desed: # Name of package - this should only be used for the TUI
    cargo: desed # Cargo package installable via `cargo install desed`
    dnf: desed # dnf package for Fedora
    github: github.com/SoptikHa2/desed # GitHub link - populate if the repository has releases
    pkg: desed # FreeBSD pkg name for future FreeBSD support
  deta:
    github: github.com/deta/deta-cli
  direnv:
    apt: direnv
    brew: direnv
    github: github.com/direnv/direnv
  docker-slim:
    brew: docker-slim
    dnf: golang-github-docker-slim
    github: github.com/docker-slim/docker-slim
    yay: docker-slim
  dockle:
    brew: goodwithtech/r/dockle
    github: github.com/goodwithtech/dockle
    yay: dockle-bin
  doctl:
    brew: doctl
    github: github.com/digitalocean/doctl
    pacman: doctl
    pkg: doctl
    snap: doctl
  dog:
    brew: dog
    github: github.com/ogham/dog
    pacman: dog
    pkg: dog
  duf:
    brew: duf
    choco: duf
    github: github.com/muesli/duf
    pacman: duf
    pkg: duf
    scoop: duf
    snap: duf-utility
  dust:
    apk: dust
    github: github.com/bootandy/dust
    pacman: dust
  envconsul:
    github: github.com/hashicorp/envconsul
  fd:
    apk: fd
    apt: fd-find
    brew: fd
    cargo: fd-find
    choco: fd
    guthub: github.com/sharkdp/fd
    pacman: fd
    pkg: fd
    scoop: fd
  felony:
    github: github.com/henryboldi/felony
  ffsend:
    apk: ffsend
    brew: ffsend
    github: github.com/timvisee/ffsend
    pkg: ffsend
    scoop: ffsend
    snap: ffsend
    yay: ffsend
  filebrowser:
    brew: filebrowser
    brew_tap: filebrowser/tap
    github: github.com/filebrowser/filebrowser
  fselect:
    brew: fselect
    choco: fselect
    cargo: fselect
    github: github.com/jhspetersson/fselect
    yay: fselect
  fuego:
    github: github.com/sgarciac/fuego
  g-assist:
    github: github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client
  ganache:
    github: github.com/trufflesuite/ganache-ui
    npm: ganache
  gitify:
    brew: gitify
    github: github.com/manosim/gitify
    yay: gitify-bin
  gitleaks:
    brew: gitleaks
    github: github.com/zricethezav/gitleaks
    pkg: gitleaks
    yay: gitleaks
  gitomatic:
    github: github.com/muesli/gitomatic
  glab:
    apk: glab
    brew: glab
    github: github.com/profclems/glab
    scoop: glab
    snap: glab
    yay: gitlab-glab-bin
  glow:
    brew: glow
    github: github.com/charmbracelet/glow
    pkg: glow
    scoop: glow
    yay: glow
  go-chromecast:
    github: github.com/vishen/go-chromecast
    go: github.com/vishen/go-chromecast
  gping:
    brew: gping
    cargo: gping
    choco: gping
    github: github.com/orf/gping
    scoop: gping
    pacman: gping
  grex:
    brew: grex
    cargo: grex
    choco: grex
    github: github.com/pemistahl/grex
    scoop: grex
  gron:
    brew: gron
    github: github.com/tomnomnom/gron
    go: github.com/tomnomnom/gron # go get -u github.com/tomnomnom/gron
  hclq:
    github: github.com/mattolenik/hclq
    go: github.com/mattolenik/hclq
  hexyl:
    apt: hexyl
    brew: hexyl
    cargo: hexyl
    github: github.com/sharkdp/hexyl
    pacman: hexyl
    pkg: hexyl
    snap: hexyl
    snoop: hexyl
  hostctl:
    brew: guumaster/tap/hostctl
    github: github.com/guumaster/hostctl
    scoop: hostctl
    yay: hostctl
  htmlq:
    brew: htmlq
    cargo: htmlq
    github: github.com/mgdm/htmlq
  hyperfine:
    apk: hyperfine
    brew: hyperfine
    cargo: hyperfine
    choco: hyperfine
    dnf: hyperfine
    github: github.com/sharkdp/hyperfine
    pacman: hyperfine
    pkg: hyperfine
  jitsi-meet-electron:
    brew: jisti-meet
    choco: jitsi-meet-electron
    github: github.com/jitsi/jitsi-meet-electron
    pkg: jisti-meet
    yay: jitsi-meet-desktop-bin
  jo:
    brew: jo
    apt: jo
    snap: jo
    github: github.com/jpmens/jo
    pkg: jo
    yay: jo
  jq:
    brew: jq
    choco: jq
    apk: jq
    apt: jq
    dnf: jq
    github: github.com/stedolan/jq
    pkg: jq
  kdash:
    brew: kdash
    brew_tap: kdash-rs/kdash
    cargo: kdash
    choco: kdash
    github: github.com/kdash-rs/kdash
    scoop: kdash
  kubenav:
    brew: kubenav
    github: github.com/kubenav/kubenav
    yay: kubenav-bin
  linuxkit:
    brew: linuxkit
    brew_tap: linuxkit/linuxkit
    github: github.com/linuxkit/linuxkit
  manta:
    brew: manta
    github: github.com/hql287/Manta
  mark-text:
    brew: mark-text
    choco: marktext
    github: github.com/marktext/marktext
    yay: marktext
  masscode:
    brew: masscode
    github: github.com/antonreshetov/massCode
  mc:
    brew: minio/stable/mc
    binary: https://dl.min.io/client/mc/release/linux-amd64/mc
    exe: https://dl.min.io/client/mc/release/windows-amd64/mc.exe
    go: github.com/minio/mc
  mjml-app:
    github: github.com/mjmlio/mjml-app
  mkcert:
    brew: mkcert
    choco: mkcert
    github: github.com/FiloSottile/mkcert
    pacman: mkcert
    scoop: mkcert
  mockoon:
    brew: mockoon
    choco: mockoon
    github: github.com/mockoon/mockoon
    snap: mockoon
    yay: mockoon-bin
  motrix:
    brew: motrix
    choco: motrix
    github: github.com/agalwood/Motrix
    scoop: motrix
    yay: motrix-bin
  mqttx:
    brew: mqttx
    github: github.com/emqx/MQTTX
    snap: mqttx
    yay: mqttx-bin
  muffet:
    brew: muffet
    github: github.com/raviqqe/muffet
    go: github.com/raviqqe/muffet/v2
    yay: muffet-bin
  mullvad-vpn:
    brew: mullvadvpn
    github: github.com/mullvad/mullvadvpn-app
    yay: mullvad-vpn
  nnn:
    apk: nnn
    apt: nnn
    brew: nnn
    github: github.com/jarun/nnn
    pacman: nnn
    pkg: nnn
  nomino:
    cargo: nomino
    github: github.com/yaa110/nomino
    yay: nomino
  nuclear:
    brew: nuclear
    choco: nuclear
    github: github.com/nukeop/nuclear
    snap: nuclear
    yay: nuclear-player-bin
  osquery:
    github: github.com/osquery/osquery
  ots:
    brew: ots
    github: github.com/sniptt-official/ots
    go: github.com/sniptt-official/ots
  oq:
    brew: oq
    github: github.com/Blacksmoke16/oq
    snap: oq
    yay: oq
  pastel:
    brew: pastel
    cargo: pastel
    github: github.com/sharkdp/pastel
    snap: pastel
    yay: pastel
  peco:
    apt: peco
    brew: peco
    choco: peco
    github: github.com/peco/peco
    pacman: peco
  pony:
    github: github.com/jessfraz/pony
    go: github.com/jessfraz/pony
  pretzel:
    github: github.com/amiechen/pretzel
  procs:
    apk: procs
    brew: procs
    cargo: procs
    dnf: procs
    github: github.com/dalance/procs
    pacman: procs
    scoop: procs # For Windows
    snap: procs
  psu:
    github: github.com/greenled/portainer-stack-utils
  pup:
    brew: pup
    github: github.com/ericchiang/pup
    go: github.com/ericchiang/pup
  q:
    brew: q
    github: github.com/harelba/q
  responsively:
    brew: responsively
    choco: responsively
    github: github.com/responsively-org/responsively-app
  rip:
    brew: rm-improved
    cargo: rm-improved
    github: github.com/nivekuil/rip
    yay: rm-improved
  runjs:
    brew: runjs
    choco: runjs
    github: github.com/lukehaas/RunJS
    snap: runjs
    yay: runjs-bin
  s5cmd:
    brew: s5cmd
    brew_tap: peak/s5cmd https://github.com/peak/s5cmd
    github: github.com/peak/s5cmd
    go: github.com/peak/s5cmd
  schema:
    go: github.com/Confbase/schema
  scrcpy:
    apt: scrcpy
    brew: scrcpy
    choco: scrcpy
    dnf: scrcpy
    github: github.com/Tomotoes/scrcpy-gui
    pkg: scrcpy
    snap: scrcpy
    yay: scrcpy
  sd:
    apk: sd # Include information about apk releases for possible future Alpine support
    brew: sd # Brew package name
    cargo: sd
    choco: sd-cli # Choco package name
    dnf: sd
    github: github.com/chmln/sd
    pacman: sd # pacman release for Archlinux
    pkg: sd
  shfmt:
    apk: shfmt
    brew: shfmt
    github: github.com/mvdan/sh/
    go: mvdan.cc/sh/v3/cmd/shfmt@latest
    pacman: shfmt
    pkg: shfmt
    scoop: shfmt
    snap: shfmt
  skm:
    brew: timothyye/tap/skm
    brew_tap: timothyye/tap
    github: github.com/TimothyYe/skm
    go: github.com/TimothyYe/skm/cmd/skm
  snitch:
    brew: little-snitch
    github: github.com/evilsocket/opensnitch
  sqlectron:
    brew: sqlectron
    github: github.com/sqlectron/sqlectron-gui
    yay: sqlectron-gui
  ssh-vault:
    brew: ssh-vault
    github: github.com/ssh-vault/ssh-vault
  ssl-proxy:
    github: github.com/suyashkumar/ssl-proxy
  switchhosts:
    github: github.com/oldj/SwitchHosts
  sysbench:
    apk: sysbench
    apt: sysbench
    brew: sysbench
    dnf: sysbench
    pacman: sysbench
    pkg: sysbench
  tabby:
    brew: tabby
    choco: tabby
    github: github.com/Eugeny/tabby
  task:
    brew: go-task/tap/go-task
    go: github.com/go-task/task/v3/cmd/task@latest
    github: github.com/go-task/task
    scoop: task
    snap: task
    yay: taskfile-git
  teleport:
    brew: teleport
    pkg: teleport
    yay: teleport-bin
  tflint:
    brew: tflint
    choco: tflint
    github: github.com/terraform-linters/tflint
  temps:
    github: github.com/jackd248/temps
  tokei:
    apk: tokei
    brew: tokei
    cargo: tokei
    choco: tokei
    dnf: tokei
    github: github.com/XAMPPRocky/tokei
    pacman: tokei
    pkg: tokei
  trivy:
    github: github.com/aquasecurity/trivy
    yay: trivy-bin
  up:
    brew: up
    github: github.com/akavel/up
    pkg: up
    yay: up
  udemy-downloader-gui:
    github: github.com/FaisalUmair/udemy-downloader-gui
  webtorrent:
    brew: webtorrent
    choco: webtorrent-desktop
    github: github.com/webtorrent/webtorrent-desktop
    yay: webtorrent-desktop
  wkhtmltopdf:
    apt: wkhtmltopdf
    brew: wkhtmltopdf
    choco: wkhtmltopdf
    github: github.com/wkhtmltopdf/wkhtmltopdf
    pacman: wkhtmltopdf
  xurls:
    go: mvdan.cc/xurls/v2/cmd/xurls
    github: github.com/mvdan/xurls
  yq:
    brew: yq
    choco: yq
    apk: yq
    github: github.com/stedolan/jq
    go: github.com/mikefarah/yq/v4
    snap: yq
