---
- name: Run project-specific tasks
  include_tasks: "install-{{ ansible_os_family }}.yml"
  loop: "{{ git_docker_projects }}"
  loop_control:
    label: "{{ project.name }}"
    loop_var: project
