---
# defaults file for ipaserver

### basic ###
ipaserver_no_host_dns: false
### server ###
ipaserver_setup_adtrust: false
ipaserver_setup_kra: false
ipaserver_setup_dns: false
ipaserver_no_hbac_allow: false
ipaserver_no_pkinit: false
ipaserver_no_ui_redirect: false
### ssl certificate ###
### client ###
ipaclient_mkhomedir: false
ipaclient_no_ntp: false
# ipaclient_ssh_trust_dns: false
# ipaclient_no_ssh: false
# ipaclient_no_sshd: false
# ipaclient_no_dns_sshfp: false
### certificate system ###
ipaserver_external_ca: false
### dns ###
ipaserver_allow_zone_overlap: false
ipaserver_no_reverse: false
ipaserver_auto_reverse: false
ipaserver_no_forwarders: false
ipaserver_auto_forwarders: false
ipaserver_no_dnssec_validation: false
### ad trust ###
ipaserver_enable_compat: false
ipaserver_setup_ca: true
### packages ###
ipaserver_install_packages: true
### firewalld ###
ipaserver_setup_firewalld: true

### additional ###
ipaserver_copy_csr_to_controller: false

### uninstall ###
ipaserver_ignore_topology_disconnect: false
ipaserver_ignore_last_of_role: false
