---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"

- name: "Set {{ app_name }} as the default browser"
  vars:
    default_browser_chosen: "{{ default_browser }}"
  include_role:
    name: helpers/defaultbrowser
  when: default_browser == 'brave'
