---
galaxy_info:
  role_name: vmware
  author: Tom Scanlan and ProfessorManhattan
  description: Install VMware Workstation on any platform
  company: VMware and Megabyte Labs
  # issue_tracker_url: http://example.com/issue/tracker
  license: "license (MIT)"

  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - precise
        - xenial
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - stretch

  galaxy_tags:
    - vmware
    - virtualization

dependencies: []
