---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure old versions of Docker are not installed
  become: yes
  block:
    - name: Ensure "docker" is not installed
      package:
        name: docker
        state: absent
    - name: Ensure "docker-common" is not installed
      package:
        name: docker-common
        state: absent
    - name: Ensure "docker-engine" is not installed
      package:
        name: docker-engine
        state: absent
  when: ansible_os_family not in ('Windows', 'Darwin')

- name: Include tasks based on the operating system
  become: yes
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when: not docker_snap_install

- name: Install Docker via snap
  become: yes
  community.general.snap:
    name: docker
  when:
    - ansible_os_family not in ('Windows', 'Darwin')
    - docker_snap_install

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: Install Docker Compose (based on OS)
  become: yes
  block:
    - include_tasks: "compose-{{ ansible_os_family }}.yml"
  when: docker_install_compose | bool

- name: Add users to the "docker" group (based on OS)
  become: yes
  block:
    - include_tasks: "users-{{ ansible_os_family }}.yml"
  when: docker_users | length > 0

- name: Determine whether TLS certificates need to be generated (non-Windows)
  become: yes
  stat:
    path: /etc/ssl/private/docker-ca.pem
  register: docker_ca_pem
  when:
    - ansible_os_family != 'Windows'
    - docker_tls | bool
    - not docker_snap_install

- name: Determine whether TLS certificates need to be generated (Windows)
  become_method: runas
  become_user: "{{ ansible_user }}"
  win_stat:
    path: C:\DockerSSLCARoot\ca.pem
  register: docker_ca_pem_win
  when:
    - ansible_os_family == 'Windows'
    - docker_tls | bool
    - not docker_snap_install

- name: Generate TLS certificates
  include_tasks: "tls-{{ ansible_os_family }}.yml"
  when:
    - docker_tls | bool
    - ansible_os_family != 'Windows'
    - not docker_ca_pem.stat.exists
    - not docker_snap_install

- name: Generate TLS certificates for Windows
  include_tasks: tls-Windows.yml
  when:
    - docker_tls | bool
    - ansible_os_family == 'Windows'
    - not docker_ca_pem_win.stat.exists
