---
- name: Run common Darwin/Linux tasks
  include_tasks: tls-Darwin-Linux.yml

- name: Add certificate to keystore # noqa 301
  become: true
  command: security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ca.pem
  args:
    chdir: "/Users/{{ ansible_user | default(lookup('env', 'USER')) }}/.docker/certs.d"

- name: Create daemon.json
  template:
    dest: "/Users/{{ ansible_user | default(lookup('env', 'USER')) }}/.docker/daemon.json"
    group: "{{ user.username }}"
    mode: 0600
    owner: "{{ user.username }}"
    src: daemon.json.j2 # TODO: This JSON file is not formatted like regular JSON - is this on purpose?

- name: Copy certificates to the ~/.docker folder on the machine running Ansible
  fetch:
    dest: "~/.docker/certs.d/{{ ansible_host }}-{{ item }}"
    flat: true
    mode: 0400
    src: "~/.docker/certs.d/{{ item }}"
  loop:
    - ca.pem
    - cert.pem
    - key.pem
  when: ansible_host != 'local'

- name: Restart the Docker Desktop app # noqa 301
  command: |
    osascript -e 'quit app "Docker"'
    open --background -a Docker
  args:
    warn: false
