---
__php_packages:
  - php
__php_webserver_daemon: "nginx"

__php_conf_paths:
  - /usr/local/etc/php/8.0/

__php_extension_conf_paths:
  - /usr/local/etc/php/8.0/

__php_apc_conf_filename: 50-apc.ini
__php_opcache_conf_filename: 10-opcache.ini
__php_fpm_daemon: php-fpm
__php_fpm_conf_path: "/usr/local/etc/php/8.0/"
__php_fpm_pool_conf_path: "/usr/local/etc/php/8.0/www.conf"

__php_fpm_pool_user: nobody
__php_fpm_pool_group: nobody

php_root_group: wheel
