---
__php_packages:
  - php

__php_webserver_daemon: "nginx"

__php_conf_paths:
  - C:/Program Files/PHP

__php_extension_conf_paths:
  - C:/Program Files/PHP

__php_apc_conf_filename: 50-apc.ini
__php_opcache_conf_filename: 10-opcache.ini
__php_fpm_daemon: php-fpm
__php_fpm_conf_path: "C:/Program Files/PHP"
__php_fpm_pool_conf_path: "C:/Program Files/PHP/www.conf"

__php_fpm_pool_user: nobody
__php_fpm_pool_group: nobody

php_opcache_zend_extension: "php_opcache.dll"

nginx_install_path: C:/Program Files/PHP
apcu_url: https://windows.php.net/downloads/pecl/releases/apcu/5.1.19/php_apcu-5.1.19-7.4-nts-vc15-x64.zip
