---
- name: Check if the fonts are present
  find:
    paths: "{{ fonts_dir + '/' + font | replace(' ','') }}"
    patterns: "(?i){{ font | replace(' ','') }}*"
    use_regex: true
  register: fonts_result

- name: "Ensure {{ fonts_dir + '/' + font | replace(' ','') }} directory exists"
  file:
    path: "{{ fonts_dir + '/' + font | replace(' ','') }}"
    state: directory
    mode: 0655

- name: "Ensure {{ font }} is installed" # noqa 501
  command: "gfi download -d {{ fonts_dir + '/' + font | replace(' ','') }} {{ font }} && fc-cache -f"
  when: fonts_result.matched > 0
