---
- name: "Ensure {{ app_name }} is installed"
  community.general.npm:
    name: google-font-installer
    global: true
    state: "{{ app_state | default('present') }}"

- name: Cycle through the list of fonts to install
  include_tasks: font-Linux.yml
  loop: "{{ fonts }}"
  loop_control:
    label: "{{ font }}"
    loop_var: font
