---
- name: Register the MAS installed apps
  command: mas list
  changed_when: false
  register: mas_list

- name: "Ensure {{ app_name }} is installed"
  command: "mas install '{{ slack_mas_id }}'"
  when: (slack_mas_id | string) not in mas_list.stdout
