---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures slackterm is installed
# Installs slackterm on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures slackterm is installed
# Ensures slackterm is available on PATH
# @action Ensures slackterm is installed
# Configures the provided Slack API key for use by slackterm
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
