---
- name: Run generic Linux tasks
  become_user: "{{ user.username }}"
  block:
    - include_tasks: install-Linux.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
