---
- name: Add Yarn's repository
  yum_repository:
    name: Yarn
    description: Repository for Yarn, a NodeJS package manager
    baseurl: "{{ yarn_yum_repo }}"
    gpgkey: "{{ yarn_gpgkey_url }}"
    gpgcheck: yes

- name: Install Yarn
  yum:
    name: packer
    state: present
    update_cache: yes
