---
- name: Add the Yarn repository GPG key
  apt_key:
    url: "{{ yarn_deb_gpg }}"
    state: present

- name: Add the Yarn apt repository
  apt_repository:
    filename: yarn
    repo: "{{ yarn_deb_repo }}"
    state: present
    update_cache: yes

- name: Install Yarn
  apt:
    name: yarn
    state: present
