---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  include_tasks: "local-{{ ansible_os_family }}.yml"
  when: ansible_connection == 'local'

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Run the configuration setup for each user
  include_tasks: user-continue.yml
  loop: "{{ user_configs | default([]) }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user

- name: Ensure user 'Ubuntu' is renamed
  become: true
  block:
    - include_tasks: linux/renameuser.yml
  when: default_username is defined
