---
- name: Update and upgrade repositories
  apt:
    cache_valid_time: 86400 # One day
    update_cache: yes
    upgrade: "yes"

- name: Install Debian common libraries and base software
  apt:
    name: "{{ debian_base_software }}"
    state: present

- name: Increase vm_max_map_count if required (Kibana)
  sysctl:
    name: vm.max_map_count
    sysctl_set: yes
    value: "262144"
  when: kibana_installed

- name: Disable wireless drivers (for Raspberry Pi)
  copy:
    src: raspi-blacklist.conf
    dest: /etc/modprobe.d/raspi-blacklist.conf
    mode: "600"
  when: disable_wireless

- name: Remove unnecessary bloatware
  apt:
    name: "{{ debian_software_to_remove }}"
    state: absent

- name: Include generic Linux tasks
  include_tasks: setup-Linux.yml
