---
- name: Ensure groups are present
  ansible.windows.win_group:
    name: "{{ group }}"
    state: present
  loop: "{{ user.groups }}"
  loop_control:
    loop_var: group
  when: user.groups is defined

- name: Ensure user belongs to configured groups
  become: true
  become_user: root
  ansible.windows.win_user:
    name: "{{ user.username }}"
    groups: "{{ user.groups }}"
    groups_action: add
  when: user.groups is defined
