---
galaxy_info:
  role_name: snapd
  author: ProfessorManhattan
  description: Installs everything needed to use snap on Linux distros
  company: Megabyte Labs
  license: license (MIT)

  min_ansible_version: 2.10

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 33
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - snap
    - snapd
    - package
    - installation
    - software
    - linux

dependencies: []
