---
- name: "Ensure {{ app_name }} is installed"
  become: false
  community.general.homebrew_cask:
    name: google-cloud-sdk
    state: "{{ app_state | default('present') }}"
    accept_external_apps: "{{ allow_external_apps | default(false) }}"

- name: "Ensure {{ app_name }}'s optional components are installed" # noqa 503
  command: "gcloud components install {{ component }}"
  loop: "{{ optional_components }}"
  loop_control:
    label: "{{ component }}"
    loop_var: component
  when: optional_components is defined

- name: "Ensure .bashrc is configured for {{ app_name }}"
  block:
    - name: "Ensure .bashrc imports {{ app_name }}'s PATH"
      become: true
      become_user: "{{ user.username }}"
      lineinfile:
        path: ~/.bashrc
        regex: \"source \"\$\(brew --prefix\)\/Caskroom\/google-cloud-sdk\/latest\/google-cloud-sdk\/path\.bash\.inc\"\"
        line: 'source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"'

    - name: "Ensure .bashrc imports {{ app_name }}'s autocompletion"
      become: true
      become_user: "{{ user.username }}"
      lineinfile:
        path: ~/.bashrc
        regex: \"source \"\$\(brew --prefix\)\/Caskroom\/google-cloud-sdk\/latest\/google-cloud-sdk\/completion\.bash\.inc\"\"
        line: 'source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"'
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
