---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Google Cloud SDK is installed
# Installs Google Cloud SDK on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures Google Cloud SDK is installed
# Installs Google Cloud SDK optional components if provided
# @action Ensures Google Cloud SDK is installed
# Ensures Google Cloud SDK tools are available in PATH
# @action Ensures Google Cloud SDK is installed
# Ensures Google Cloud SDK completions are setup
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
