---
- name: "Add {{ app_name }}'s apt repository"
  apt_repository:
    filename: "{{ app_name | lower | replace(' ', '-') }}"
    repo: "{{ lollypop_apt_repository }}"
    state: present
    update_cache: true

- name: "Ensure {{ app_name }} is installed"
  apt:
    name: lollypop
    state: "{{ app_state | default('present') }}"
