---
propagate:projects:
  image: megabytelabs/propagate:slim
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_TITLE =~ /^chore.*/
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $PROPAGATE_FILES == 'true'
  script:
    - set -eo pipefail
    - curl -o propagate.sh https://gitlab.com/megabyte-labs/ci/gitlab-ci-templates/-/raw/master/scripts/propagate-projects.sh
    - bash propagate.sh
  stage: deploy
  variables:
    GIT_DEPTH: 1
