---
propagate:projects:
  stage: deploy
  image: megabytelabs/propagate:slim
  rules:
    - if: $REPOSITORY_TYPE == 'documentation' && $PIPELINE_SOURCE == $COMMON_SHARED_PROJECT_ID
      when: never
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_TITLE =~ /^chore.*/
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $PROPAGATE_FILES == 'true'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - curl -o propagate.sh https://gitlab.com/megabyte-labs/common/shared/-/raw/master/common/.gitlab/ci/scripts/propagate-projects.sh
    - bash propagate.sh
