---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures ghorg is installed
# Installs ghorg on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures ghorg is installed
# Configures ghorg with the provided settings
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
