---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Register Homebrew bin path information
  stat:
    path: "{{ homebrew_bin_path }}"
  register: brew_bin

- name: Install Homebrew
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when: not brew_bin.stat.exists

- name: Ensure .bashrc includes Homebrew (Linux) # TODO: Add the equiavalent to Mac OS X and Windows
  include_tasks: bashrc-Linux.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
  when: ansible_system == 'Linux'

- name: Ensure Homebrew packages are installed and up-to-date
  community.general.homebrew: # TODO: Test to see if Windows supports the Ansible homebrew module
    name: "{{ package.name }}"
    path: "{{ homebrew_bin_path }}"
    state: present
    update_homebrew: true
    upgrade_all: true
  loop: "{{ homebrew_packages | default([]) }}"
  loop_control:
    label: "{{ package.name }}"
    loop_var: package
