---
- name: Detect presence of the user home directory
  stat:
    path: "/home/{{ user.username }}"
  register: user_home_directory

- name: Ensure Flameshot configuration folder exists
  become: true
  become_user: "{{ user.username }}"
  file:
    path: "{{ item }}"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: 0700
    state: directory
  loop:
    - ~/.config
    - ~/.config/Dharkael
  when: user_home_directory.stat.exists

- name: Copy Flameshot configuration
  become: true
  become_user: "{{ user.username }}"
  template:
    src: flameshot.ini.j2
    dest: ~/.config/Dharkael/flameshot.ini
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: 0664
  when: user_home_directory.stat.exists
