---
- name: "Ensure {{ app_name }} is installed"
  apt:
    name: flameshot
    state: "{{ app_state | default('present') }}"

- name: Add Flameshot configuration to users
  include_tasks: config-Linux.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
