---
- name: Add .vault_pass file for automation purposes
  template:
    src: vault_password.j2
    dest: ~/Playbooks/.vault_pass
    owner: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    group: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    mode: 0600

- name: Add labels to hard drives
  become: true
  command: "e2label {{ item.path }} {{ item.label }}"
  loop:
    - path: /dev/sda
      label: Movies
    - path: /dev/sdb
      label: TV
    - path: /dev/nvme0n1
      label: Auxilary

- name: Ensure /etc/fstab has proper entries
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "LABEL=Movies"
      line: LABEL=Movies /mnt/movies auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=Movies 0 0
    - regexp: "LABEL=TV"
      line: LABEL=TV /mnt/tv auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=TV%20Shows 0 0
    - regexp: "LABEL=Auxilary"
      line: LABEL=Auxilary /mnt/auxilary auto nosuid,nodev,nofail,x-gvfs-show,x-gvfs-name=Auxilary 0 0

- name: Ensure ~/.config/autostart exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - ~/.config
    - ~/.config/autostart

- name: Copy ansible-installer.desktop to ~/.config/autostart (for continuing the installation after reboot)
  copy:
    src: files/ubuntu/ansible-installer.desktop
    dest: ~/.config/autostart/ansible-installer.desktop
    mode: 0700

- name: Reboot
  become: true
  command: reboot
