---
- name: Include variables based on the operating system 
  include_vars: "{{ ansible_os_family }}.yml"

- name: Loop through users and add dotfiles
  include_tasks: user-continue.yml
  loop: "{{ user_configs | default([]) }}"
  loop_control:
    loop_var: user
