---
- name: Add static dotfiles
  win_copy:
    src: "{{ item }}"
    dest: "{{ user_profile }}\\{{ item }}"
  with_items:
    - .localrc
    - .zshrc

- name: Add dynamic dotfiles
  win_template:
    src: "{{ item }}.j2"
    dest: "{{ user_profile }}\\{{ item }}"
  with_items:
    - .gitconfig
    - .netrc
    - .npmrc

- name: Determine whether the user's .bashrc file is present in the home directory
  win_stat:
    path: ~/.bashrc
  register: bashrc

- name: Ensure .bashrc exists in user's home directory
  win_file:
    path: "{{ user_profile }}\\.bashrc"
    state: touch
  ignore_errors: true
  when: not bashrc.stat.exists

- name: Ensure .localrc is sourced in .bashrc
  win_lineinfile:
    path: "{{ user_profile }}\\.bashrc"
    regex: "^source ~\/.localrc$"
    line: source ~/.localrc
