---
- name: Add Restic's repository
  copy:
    src: "{{ restic_repo }}"
    dest: "{{ repos_dir }}/{{ restic_repo }}"
    mode: preserve

- name: Install Restic
  dnf:
    name: restic
    state: present
