---
# You should definitely customize these!
pihole_admin_email: help@example.com
pihole_ipv4_address: 192.168.1.14/24

# Optional ways to customize pihole-setupVars.conf
# https://discourse.pi-hole.net/t/what-is-setupvars-conf-and-how-do-i-use-it/3533
pihole_ipv6_address:
pihole_query_logging: true
pihole_install_web: true
pihole_lighttpd_enabled: 1
pihole_api_exclude_domains:
pihole_api_exclude_clients:
pihole_api_query_log_show: all
pihole_api_privacy_mode: false
pihole_webuiboxedlayout: boxed
pihole_webtheme: default-dark
pihole_dnsmasq_listening: single
pihole_dns_1: 127.0.0.1#5053
pihole_dns_fqdn_required: true
pihole_dns_bogus_priv: true
pihole_dnssec: false
pihole_rev_server: false
pihole_temperatureunit: F