---
sonarcloud:
  stage: lint
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  only:
    - merge_requests
    - master
    - develop
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
  variables:
    GIT_DEPTH: '0'
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - set -eo pipefail
    - sonar-scanner
