---
# @action Ensures Appium is installed
# Installs Appium on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures Appium is installed
# Installs Appium Desktop on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures Appium is installed
# Installs Appium Inspector on Archlinux, CentOS, Debian, Fedora and Ubuntu
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
