---
# TODO: Only run the command when the value needs to be changed
- name: Apply extension settings # noqa 301
  become: true
  become_user: "{{ user.username }}"
  command: "{{ setting }}"
  loop: "{{ item.settings | default([]) }}"
  loop_control:
    loop_var: setting
