---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_system == 'Linux'

- name: Loop through the users in the configuration
  include_tasks: user.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
  when:
    - not (user.system | default(false))
    - ansible_system == 'Linux'
