---
lint:eslint:
  stage: lint
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  allow_failure: true
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.{js,jsx,json,json.handlebars,toml,ts,tsx,yml}'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - eslint --format gitlab . # Requires eslint-formatter-gitlab
