---
lint:standard:
  stage: lint
  image:
    name: megabytelabs/standard:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.js'
  variables:
    GIT_DEPTH: 1
  before_script:
    - git config pull.ff only
    - git checkout "$CI_COMMIT_REF_NAME"
    - git pull origin "$CI_COMMIT_REF_NAME"
  script:
    - set -eo pipefail
    - standard
