---
- name: "Ensure {{ app_name }} is installed"
  community.general.snap:
    name: googler
    state: "{{ app_state | default('present') }}"

- name: "Ensure completions directory exists"
  file:
    path: /usr/local/src/googler/
    state: directory
    mode: 0644

- name: "Ensure bash completions are downloaded"
  get_url:
    src: "{{ item.url }}"
    dest: "{{ item.path }}"
    mode: 0644
  with_items:
    - url: https://raw.githubusercontent.com/jarun/googler/master/auto-completion/bash/googler-completion.bash
      path: /usr/local/src/googler/googler-completion.bash
    - url: https://raw.githubusercontent.com/jarun/googler/master/auto-completion/googler_at/googler_at
      path: /usr/local/src/googler/googler_at
