---
lint:gitlab-ci:
  stage: lint
  image:
    name: megabytelabs/gitlab-ci-lint:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*gitlab-ci.yml'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - printenv
    - find . -type f -name \*.gitlab-ci.yml -print0 | xargs -0 -r -n1 gitlab-ci-lint --token "$GROUP_ACCESS_TOKEN"
