---
vagrant:validate:
  stage: lint
  image:
    name: megabytelabs/vagrant:slim
    entrypoint: ['']
  allow_failure: true
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/Vagrantfile'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - find . -type f -name 'Vagrantfile' -exec bash -c 'INITIAL_DIR=$PWD; VAGRANTFILE_PATH=$1;
      cd $(dirname $VAGRANTFILE_PATH); vagrant validate; cd $INITIAL_DIR' _ {} \;
