---
# Brotli
brotli_dependencies:
  - base-devel
  - cmake
  - gcc
  - pcre
  - openssl
  - zlib

# ModSecurity
modsec_dependencies:
  - git
  - curl
  - geoip
  - lus52
  - libxml2
  - pcre2
  - yajl
  - ssdeep
modsec_waf_conf_directory: /etc/nginx/modsec/owasp-modsecurity-crs

# NGINX
nginx_dependencies:
  - git
  - nginx
  - openssl
nginx_module_link: /usr/share/nginx/modules
nginx_service_path: /usr/lib/systemd/system/nginx.service

# Miscellaneous
dhparam_path: /etc/ssl/certs/dhparam.pem
error_page_directory: /var/www/html
