---
# Amplify
amplify_apt_key_url: https://nginx.org/keys/nginx_signing.key
amplify_apt_repository: "deb http://packages.amplify.nginx.com/{{ ansible_distribution }}/ {{ ansible_distribution_release }} amplify-agent"

# Brotli
brotli_dependencies: # TODO: After Brotli is compiled, remove unnecessary dependencies
  - cmake
  - gcc
  - libpcre3
  - libpcre3-dev
  - libssl-dev
  - zlib1g
  - zlib1g-dev

# ModSecurity
modsec_dependencies: # TODO: After modsec is compiled, remove unnecessary dependencies
  - build-essential
  - git
  - libcurl4-openssl-dev
  - libfuzzy-dev
  - libgeoip-dev
  - liblua5.2-dev
  - libpcre++-dev
  - libpcre3-dev
  - libxml2-dev
  - libyajl-dev
  - ssdeep
modsec_waf_conf_directory: /etc/nginx/modsec/owasp-modsecurity-crs

# NGINX
nginx_dependencies:
  - git
  - nginx
  - openssl
nginx_module_link: /usr/share/nginx/modules
nginx_service_path:
  Debian: /lib/systemd/system/nginx.service
  Ubuntu: /usr/lib/systemd/system/nginx.service

# Miscellaneous
dhparam_path: /etc/ssl/certs/dhparam.pem
error_page_directory: /var/www/html
