---
- name: "Ensure {{ app_name }}'s Tap is installed"
  become: false
  community.general.homebrew_tap:
    name: miserlou/loop
    url: https://github.com/Miserlou/Loop.git

- name: "Ensure {{ app_name }} is installed"
  become: false
  community.general.homebrew:
    name: loop
    state: "{{ app_state | default('head') }}"
