---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures gitlab-runner is installed
# Installs gitlab-runner on Archlinux, CentOS, Debian, Fedora, Ubuntu, MacOS and Windows
# @action Ensures gitlab-runner is configured
# Registers gitlab-runner
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
