---
- name: Copy .hyper.js
  win_copy:
    src: .hyper.js
    dest: "{{ user_profile }}\\.hyper.js"

- name: Update font size in .hyper.js for Windows
  win_lineinfile:
    path: "{{ user_profile }}\\.hyper.js"
    regex: "fontSize: 12,"
    line: "fontSize: 15,"
