---
- name: Add .hyper.js to user's home directory
  become: true
  become_user: "{{ user.username }}"
  copy:
    src: .hyper.js
    dest: ~/.hyper.js
    owner: "{{ user.username }}"
    group: "{{ user.group | default(user.username) }}"
    mode: 0600
