---
- name: "Ensure {{ app_name }} is installed"
  dnf:
    name: "{{ hyper_rpm_url }}"
    state: "{{ app_state | default('present') }}"

- name: Ensure Fira Code font is installed
  include_role:
    name: helpers/fontinstall
  vars:
    fonts:
      - fira code
  when: install_fira_code
