---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Configure HyperJS
  include_tasks: "config-{{ ansible_os_family }}.yml"
  loop: "{{ hyper_users }}"
  loop_control:
    loop_var: user
