---
- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert

- name: Stop services to allow certbot to generate a cert
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ certbot_create_standalone_stop_services }}"
  when: not letsencrypt_cert.stat.exists

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists

- name: Start services after cert has been generated
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ certbot_create_standalone_stop_services }}"
  when: not letsencrypt_cert.stat.exists
