---
galaxy_info:
  role_name: nmap
  author: ProfessorManhattan
  description: Installs nmap on nearly any platform
  company: Megabyte Labs
  # issue_tracker_url: https://gitlab.com/ProfessorManhattan/Playbooks/-/issues
  license: license (MIT)

  min_ansible_version: 2.10

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Mac OS X
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
    - name: Windows
      versions:
        - 10

  galaxy_tags:
    - nmap
    - network
    - monitor
    - discovery
    - audit
    - inventory

dependencies: []
