---
- name: "Ensure WireGuard nmconnection files are copied"
  copy:
    src: "files/vpn/{{ vpn_connection.file }}"
    dest: "{{ system_connections_path }}/{{ vpn_connection.file }}"
    owner: root
    group: root
    mode: 0600
  notify: restart networkmanager
