---
galaxy_info:
  role_name: skype
  author: ProfessorManhattan
  description: Installs Skype on nearly any platform
  company: Megabyte Labs
  issue_tracker_url: https://gitlab.com/megabyte-labs/ansible-roles/skype/-/issues
  license: license (MIT)

  min_ansible_version: 2.10

  platforms:
    - name: Archlinux
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - 32
    - name: Ubuntu
      versions:
        - focal
    - name: Windows
      versions:
        - 10

  galaxy_tags:
    - skype
    - microsoft
    - collaboration
    - conference
    - screenshare
    - voip
    - video
    - webcam

dependencies:
  - role: homebrew
    when: ansible_os_family == 'Darwin'
  - role: snapd
    when: ansible_system == 'Linux'
