---
- name: Enroll target in Fleet # TODO: Check if it is already enrolled and skip this if so
  become: true
  shell: "elastic-agent enroll {{ kibana_url }} {{ kibana_enrollment_secrets[kibana_enrollment_id] }} --force"
  notify: restart elastic-agent
  when:
    - kibana_enrollment_id is defined
    - kibana_enrollment_secrets[kibana_enrollment_id] is defined
