---
- name: "Ensure {{ app_name }} is installed (64-bit client)" # TODO: Add verification with sha/asc found here: https://www.elastic.co/downloads/elastic-agent
  apt:
    deb: "{{ elastic_agent_64_deb_url }}"
  when: ansible_architecture == 'x86_64' or ansible_architecture == 'aarch64'

- name: "Ensure {{ app_name }} is installed (32-bit client)"
  apt:
    deb: "{{ elastic_agent_32_deb_url }}"
  when:
    - ansible_architecture != 'x86_64'
    - ansible_architecture != 'aarch64'

- name: Enroll the client in the Kibana Fleet
  include_tasks: enroll-Linux.yml
