---
- name: "Ensure {{ app_name }} is installed (64-bit client)"
  yum:
    name: "{{ elastic_agent_64_rpm_url }}"
  when: ansible_architecture == 'x86_64' or ansible_architecture == 'aarch64'

- name: "Ensure {{ app_name }} is installed (32-bit client)"
  yum:
    name: "{{ elastic_agent_32_rpm_url }}"
  when:
    - ansible_architecture != 'x86_64'
    - ansible_architecture != 'aarch64'

- name: Enroll the client in the Kibana Fleet
  include_tasks: enroll-Linux.yml
