---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Windows'

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family != 'Windows'
    - ansible_facts['virtualization_type'] != "NA"

- name: Run user-specific tasks
  include_tasks: "user-{{ ansible_os_family }}.yml"
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
  when:
    - ansible_system == 'Linux'
    - ansible_facts['virtualization_type'] != "NA"
