---
user_configs: []
# The user_configs configuration below will add the ansible_user
# to the groups necessary to administer KVM instances but it will
# not add the root user.
### EXAMPLE ###
# user_configs:
#   - username: "{{ ansible_user }}"
#     kvm_admin: true
#   - username: root
