---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Ensure global pip packages are installed
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  loop: "{{ pip_packages }}"

- name: "Ensure PIP Packages are installed"
  become: true
  block:
    - include_tasks: pip-users.yml
