---
# @var theme_slug: ""
# The slug / folder name of the theme
theme_slug: betelgeuse

# @var user_configs: []
# The `user_configs` variable is an array of objects that should, at the very
# least have the `username` property defined for each user with a home directory
# that you would like this role to install the Android SDK tools into. If the
# system property is set to true, then the SDK tools will not be installed to that
# user's home directory. You can control the installation location with the `sdk_location`
# variable.
# @example #
# user_configs:
#   - username: myuser
#   - username: root
#     system: true
# @end
user_configs: []
