---
- name: "Ensure {{ app_name }}'s yum repository is added"
  yum_repository:
    baseurl: "{{ vault_yum_repo }}"
    description: HashiCorp repository
    gpgcheck: true
    gpgkey: "{{ vault_gpgkey_url }}"
    name: HashiCorp
  when: ansible_distribution != 'Fedora'

- name: "Ensure {{ app_name }}'s yum repository is added (Fedora)"
  yum_repository:
    baseurl: "{{ vault_dnf_repo }}"
    description: HashiCorp repository
    gpgcheck: true
    gpgkey: "{{ vault_gpgkey_url }}"
    name: HashiCorp
  when: ansible_distribution == 'Fedora'

- name: "Ensure {{ app_name }} is installed"
  package:
    name: vault
    state: present
