---
- name: "Ensure {{ app_name }}'s apt repository key is added"
  apt_key:
    url: "{{ vault_deb_gpg }}"
    state: present

- name: "Ensure {{ app_name }}'s apt repository is added"
  apt_repository:
    filename: HashiCorp
    repo: "{{ vault_deb_repo }}"
    state: present
    update_cache: true

- name: "Ensure {{ app_name }} is installed"
  apt:
    name: vault
    state: present
