---
asdf_plugin_dependencies:
  - autoconf
  - awk
  - bison
  - build-essential
  - curl
  - default-libmysqlclient-dev
  - gettext
  - git
  - grep
  - libbz2-dev
  - libcurl4-openssl-dev
  - libedit-dev
  - libffi-dev
  - libgd-dev
  - libicu-dev
  - libjpeg-dev
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libonig-dev
  - libpng-dev
  - libpq-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libzip-dev
  - llvm
  - make
  - openssl
  - pkg-config
  - re2c
  - sed
  - tar
  - tk-dev
  - unzip
  - wget
  - xz-utils
  - zip
  - zlib1g-dev
