---
- name: "Make sure .bashrc imports {{ app_name }}"
  become: true
  become_user: "{{ user.username }}"
  lineinfile:
    path: ~/.bashrc
    regex: \"{{ homebrew_bin_path | replace('/', '\\/') }}\/opt\/mcfly\/mcfly\.bash\"
    line: "source {{ homebrew_bin_path }}/opt/mcfly/mcfly.bash"
