---
- name: "Ensure {{ app_name }}'s Tap is installed"
  community.general.homebrew_tap:
    name: cantino/mcfly
    url: https://github.com/cantino/mcfly

- name: "Ensure {{ app_name }} is installed"
  community.general.homebrew:
    name: mcfly
    state: "{{ app_state | default('present') }}"

- name: "Ensure .bashrc includes McFly"
  include_tasks: bashrc-Linux.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
