---
roles:
  - name: professormanhattan.homebrew
  - name: professormanhattan.nodejs
collections:
  - name: chocolatey.chocolatey
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: google.cloud
    source: https://galaxy.ansible.com
