---
galaxy_info:
  role_name: cloudflared
  namespace: professormanhattan
  author: ProfessorManhattan
  description: Installs Argo Tunnel Client on nearly any system
  company: Megabyte Labs
  issue_tracker_url: https://gitlab.com/megabyte-labs/ansible-roles/cloudflared/-/issues
  license: license (MIT)
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 7
    - name: Windows
      versions:
        - all
    - name: MacOS
      versions:
        - all
  galaxy_tags:
    - ansible
    - argo
    - cloudflare
    - debian
    - doctor
    - fedora
    - install
    - installdoc
    - installdoctor
    - macos
    - mblabs
    - megabytelabs
    - molecule
    - privacy
    - professormanhattan
    - role
    - tunnel
    - ubuntu
    - washingtondc
    - windows
dependencies: []
