---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Firewall is configured
# Installs UFW firewall on Linux Systems
# @action Ensures Firewall is configured
# Configures common Firewall rules
# @action Ensures Firewall is configured
# Enables Firewall logging
# @action Ensures Firewall is configured
# Configures SSH and RDP access
# @action Ensures Firewall is configured
# Configures access to Apt-cacher-ng
# @action Ensures Firewall is configured
# Configures remote access to Docker daemon
# @action Ensures Firewall is configured
# Configures access to Plex Media Server
# @action Ensures Firewall is configured
# Configures access to TFTP server
# @action Ensures Firewall is configured
# Configures access to UniFi
# @action Ensures Firewall is configured
# Configures access to MAAS
# @action Ensures Firewall is configured
# Configures access to HTTP/HTTPS services
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "setup-{{ ansible_os_family }}.yml"
