---
# yamllint disable rule:line-length
user_configs:
  - username: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    app_images: true
    cocoapods_specs: true
    dconf_settings:
      - key: /org/gnome/desktop/background/picture-uri
        value: "'file:///usr/share/backgrounds/brad-huchteman-stone-mountain.jpg'"
      - key: /org/gnome/shell/favorite-apps
        value: "['org.gnome.Nautilus.desktop', 'firefox.desktop', 'chromium_chromium.desktop', \
          'brave-browser.desktop', 'mailspring_mailspring.desktop', 'code_code.desktop', \
          'hyper.desktop', 'plexmediaserver_pms-web.desktop', 'org.gnome.Lollypop.desktop', \
          'virt-manager.desktop', 'vmware-workstation.desktop']"
      - key: /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size
        value: '40'
      - key: /org/gnome/desktop/session/idle-delay
        value: '600'
      - key: /org/gnome/desktop/privacy/report-technical-problems
        value: 'false'
    git_user_email: '{{ git_user_email }}'
    git_user_name: '{{ git_user_name }}'
    intellij_plugins:
      - https://plugins.jetbrains.com/plugin/7212-cucumber-for-java
      - https://plugins.jetbrains.com/plugin/9164-gherkin
    gnome_extensions:
      - url: https://extensions.gnome.org/extension/750/openweather/
        regex: openweather-extension
        settings:
          - "gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de\
            /schemas/ set org.gnome.shell.extensions.openweather city '40.7970384,-74.4809492>Morristown, \
            Morris County, New Jersey, 07960, United States of America >-1 && 40.7127281,-74.0060152>New \
            York, United States of America >-1 && 12.9791198,77.5912997>Bengaluru, Bangalore North, \
            Bangalore Urban, Karnataka, India >-1 && 40.4862174,-74.4518173>New Brunswick, New Jersey, \
            United States of America >-1'"
          - gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/schemas/ set org.gnome.shell.extensions.openweather days-forecast 10
          - gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/schemas/ set org.gnome.shell.extensions.openweather show-text-in-panel true
          - gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/schemas/ set org.gnome.shell.extensions.openweather actual-city 0
      - url: https://extensions.gnome.org/extension/771/proxy-switcher/
        regex: ProxySwitcher
      - url: https://extensions.gnome.org/extension/1085/simple-net-speed/
        regex: simplenetspeed
      - url: https://extensions.gnome.org/extension/906/sound-output-device-chooser/
        regex: sound-output-device-chooser
      - url: https://extensions.gnome.org/extension/2983/ip-finder/
        regex: IP-Finder
      - url: https://extensions.gnome.org/extension/6/applications-menu/
        regex: apps-menu
      - url: https://extensions.gnome.org/extension/3061/vlan-switcher/
        regex: vlan-switcher
      - url: https://extensions.gnome.org/extension/1762/lan-ip-address/
        regex: lan-ip-address
      - url: https://extensions.gnome.org/extension/2224/easy-docker-containers/
        regex: easy_docker_containers
    groups: # This link may be useful for determining which groups to add a user to https://wiki.debian.org/SystemGroups
      - lpadmin # Allows members to manage printers and pending jobs sent by other users
    kvm_admin: true
    netrc_hosts:
      - machine: surge.surge.sh
        username: '{{ surgesh_username }}'
        password: '{{ surgesh_password }}'
    ngrok_token: '{{ ngrok_token }}'
    npm_author_email: '{{ npm_author_email }}'
    npm_author_name: '{{ npm_author_name }}'
    npm_author_url: https://megabyte.space
    pips:
      - pipx
    rclone:
      - name: Digital Ocean
        provider: digitalocean
        config: |
          type = s3
          env_auth = false
          access_key_id = {{ digitalocean_access_key_id }}
          secret_access_key = {{ digitalocean_secret_access_key }}
          endpoint = nyc3.digitaloceanspaces.com
          acl = private
      - name: Dropbox
        provider: dropbox
        config: |
          type = dropbox
          token = {"access_token":"{{ dropbox_access_token }}","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
      - name: Google
        provider: google
        config: |
          type = drive
          client_id = {{ google_drive_client_id }}
          client_secret = {{ google_drive_client_secret }}
          scope = drive
          token = {"access_token":"{{ google_drive_access_token }}","token_type":"Bearer","refresh_token":"{{ google_drive_refresh_token }}","expiry":"2020-08-12T00:45:51.652771516-04:00"}
          root_folder_id = {{ google_drive_root_folder_id }}
      - name: Google (Work)
        provider: google-work
        config: |
          type = drive
          client_id = {{ google_drive_work_client_id }}
          client_secret = {{ google_drive_work_client_secret }}
          scope = drive
          token = {"access_token":"{{ google_drive_access_token }}","token_type":"Bearer","refresh_token":"{{ google_drive_work_refresh_token }}","expiry":"2020-08-12T00:56:15.502399692-04:00"}
      - name: OneDrive
        provider: onedrive
        config: |
          type = onedrive
          token = {"access_token":"{{ onedrive_access_token }}","token_type":"Bearer","refresh_token":"{{ onedrive_refresh_token }}","expiry":"2020-08-12T00:47:01.9828663-04:00"}
          drive_id = {{ onedrive_drive_id }}
          drive_type = personal
    samba_user: true
    # ssh_authorized_keys:
    #   - "{{ lookup('file', 'files/ssh/id_rsa_local.pub') }}"
    ssh_private_keys:
      - files/ssh/id_rsa
      - files/ssh/id_rsa_do
      - files/ssh/id_rsa_kuber_local
      - files/ssh/id_rsa_local
      - files/ssh/id_rsa_pfsense
      - files/ssh/id_rsa_unifi
      - files/ssh/id_rsa_web
    symlinks:
      - path: /mnt/auxilary/Camera
        link: ~/Pictures/Camera
        create: /mnt/auxilary
      - path: /mnt/auxilary/Games
        link: ~/Games
      - path: /mnt/auxilary/Music
        link: ~/Music/Library
      - path: /mnt/movies
        link: ~/Videos/Movies
      - path: /mnt/auxilary/Music Videos
        link: ~/Videos/Music Videos
      - path: /mnt/auxilary/Shorts
        link: ~/Videos/Shorts
      - path: /mnt/tv
        link: ~/Videos/TV
      - create: /mnt/htpc # Does not support relative paths
        path: /mnt/movies
        link: /mnt/htpc/Movies
      - path: /mnt/auxilary/Music Videos
        link: /mnt/htpc/Music Videos
      - path: /mnt/tv
        link: /mnt/htpc/TV
      - path: /mnt/auxilary/Shorts
        link: /mnt/htpc/Shorts
      - path: /mnt/auxilary/Games
        link: /mnt/htpc/Games
      - path: /mnt/auxilary/Music
        link: /mnt/htpc/Music
    tinypng_api_key: '{{ tinypng_api_key }}'
    vagrant_cloud_token: '{{ vagrant_cloud_token }}'
    vscode_extensions: '{{ vscode_extensions }}'
  - username: root
    git_user_email: '{{ git_user_email }}'
    git_user_name: '{{ git_user_name }}'
    ssh_private_keys:
      - files/ssh/id_rsa_web
    system: true
