---
- name: Ensure git-lfs is installed
  community.general.pacman:
    name: git-lfs
    state: present
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"
  register: install_result

- name: Ensure git-lfs global configuration is run # noqa 303 503
  command: git lfs install --system
  when: install_result.changed
