---
- name: Ensure git-lfs is installed
  chocolatey.chocolatey.win_chocolatey:
    name: git-lfs
    state: present
  register: install_result

- name: Ensure git-lfs global configuration is run # noqa 303 503
  ansible.windows.win_command: git lfs install --system
  when: install_result.changed
