---
- name: "Ensure {{ app_name }} is installed"
  become: false
  community.general.homebrew:
    name: git-lfs
    state: present
  register: install_result

- name: Ensure git-lfs global configuration is run # noqa 303 503
  become: false
  command: git lfs install
  when: install_result.changed
