---
- name: Register the MAS installed apps
  command: mas list
  register: mas_list
  changed_when: false

- name: Ensure Microsoft Remote Desktop is installed
  command: "mas install '{{ microsoft_remote_desktop_mas_id }}'"
  when: (microsoft_remote_desktop_mas_id | string) not in mas_list.stdout
