---
- name: List installed MAS apps
  command: mas list
  register: mas_list
  changed_when: false

- name: Ensure configured MAS apps are installed
  command: "mas install '{{ item.id | default(item) }}'"
  loop: "{{ mas_desktop_software }}"
  when: (item.id | string) not in mas_list.stdout

- name: Upgrade all apps (if configured)
  command: mas upgrade
  when: mas_upgrade_all_apps
