---
# @var plugin_folder_prefix: ~/.local/share/JetBrains/IdeaIC
# The prefix of the path to the Plugins directory. The end part of this value, which depends on the version of
# IntelliJ IDEA will be determined based on the version installed
plugin_folder_prefix: ~/.local/share/JetBrains/IdeaIC
