---
vault_dnf_repo: "https://rpm.releases.hashicorp.com/fedora/hashicorp.repo"
vault_gpgkey_url: "https://rpm.releases.hashicorp.com/gpg"
vault_yum_repo: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
