---
- name: 'Check the gsetting (gsettings get {{ item.setting }})'
  become_user: '{{ user.username }}'
  command: 'gsettings get {{ item.setting }}'
  register: gsettings_get_command
  changed_when: false
  failed_when: false

- name: 'Apply the gsetting (gsettings set {{ item.setting }} {{ item.value }})'
  become_user: '{{ user.username }}'
  command: gsettings set {{ item.setting }} {{ item.value }}
  when:
    - gsettings_get_command.rc == 0
    - gsettings_get_command.stdout != item.value
    - gsettings_get_command.stdout != ("''" + item.value + "''")
