---
- name: Check if the {{ item }} desktop shortcut exists
  stat:
    path: "/usr/share/applications/{{ item }}"
  register: sys_tool_link

- name: Backup the {{ item }} shortcut to /usr/share/applications/hidden
  copy:
    src: "/usr/share/applications/{{ item }}"
    dest: "/usr/share/applications/hidden/{{ item }}"
    remote_src: true
  when: sys_tool_link.stat.exists

- name: Remove the {{ item }} shortcut
  file:
    path: "{{ item }}"
    state: absent
  when: sys_tool_link.stat.exists
