---
- name: "Ensure {{ app_name }} is installed" # TODO: APPX install
  debug:
    msg: "TODO: Figure out how to install Microsoft Office APPX from the Microsoft Store"

- name: Remove Microsoft Office Tools folder from the Start Menu
  win_file:
    path: "{{ windows_startmenu }}\\Microsoft Office Tools"
    state: absent
