---
- name: List installed MAS apps
  become: false
  command: mas list
  register: mas_list
  changed_when: false

- name: Ensure Apple Office/Productivity apps are installed
  become: false
  command: "mas install '{{ item.id | default(item) }}'"
  loop: "{{ mas_apple_office_software }}"
  when: (item.id | string) not in mas_list.stdout

- name: Ensure Microsoft Office apps are installed
  become: false
  command: "mas install '{{ item.id | default(item) }}'"
  loop: "{{ mas_microsoft_office_software }}"
  when: (item.id | string) not in mas_list.stdout
