---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Microsoft Office is installed
# Installs Microsoft Office on macOS and Windows
# @action Ensures Libreoffice is installed
# Installs Libreoffice on Archlinux, CentOS, Debian, Fedora nad Ubuntu
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
