---
galaxy_info:
  role_name: deno
  namespace: professormanhattan
  author: ProfessorManhattan
  description: Installs Deno (an alternative to Node.js that supports TypeScript and
    is built with security in mind) on nearly any platform
  company: Megabyte Labs
  issue_tracker_url: https://gitlab.com/megabyte-labs/ansible-roles/deno/-/issues
  license: license (MIT)
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 7
    - name: Archlinux
      versions:
        - all
    - name: Windows
      versions:
        - all
    - name: MacOS
      versions:
        - all
  galaxy_tags:
    - ansible
    - doctor
    - fedora
    - install
    - installdoc
    - installdoctor
    - javascript
    - js
    - macos
    - mblabs
    - megabytelabs
    - molecule
    - professormanhattan
    - role
    - runtime
    - typescript
    - ubuntu
    - washingtondc
    - web
    - windows
dependencies:
  - role: professormanhattan.homebrew
    when: ansible_os_family == "Darwin"
