---
homebrew_casks:
  # @action Homebrew Packages # [clocker](https://formulae.brew.sh/cask/clocker)
  # macOS program that shows the time in multiple timezones in the top menu bar
  - name: clocker
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @action Homebrew Packages # [sloth](https://github.com/sveinbjornt/Sloth)
  # macOS program that shows all open files, directories, sockets, pipes, and devices in use by all running processes on the system
  - name: sloth
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @action Homebrew Packages # [stats](https://formulae.brew.sh/cask/stats)
  # macOS program that shows the system monitor in the top menu bar
  - name: stats
    when: "{{ ansible_os_family == 'Darwin' }}"

homebrew_packages:
  # @action Homebrew Packages # [automake](https://formulae.brew.sh/formula/automake)
  # Tool for generating GNU Standards-compliant Makefiles
  - name: automake

  # @action Homebrew Packages # [carthage](https://formulae.brew.sh/formula/carthage)
  # A simple, decentralized dependency manager for Cocoa 
  - name: carthage
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @action Homebrew Packages # [chrome-cli](https://formulae.brew.sh/formula/chrome-cli)
  # Control Google Chrome from the command-line
  - name: chrome-cli
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @action Homebrew Packages # [findutils](https://formulae.brew.sh/formula/findutils)
  # Collection of GNU find, xargs, and locate
  - name: findutils

  # @action Homebrew Packages # [ideviceinstaller](https://formulae.brew.sh/formula/ideviceinstaller)
  # Tool for managing apps on iOS devices
  - name: ideviceinstaller

  # @action Homebrew Packages # [libimobiledevice](https://formulae.brew.sh/formula/libimobiledevice)
  # Library to communicate with iOS devices natively
  - name: libimobiledevice
