---
# yamllint disable rule:line-length
nodejs_npm_global_packages:
  # @npm [@angular/cli](https://npmjs.com/package/@angular/cli) | [GitHub](https://github.com/angular/angular-cli) - Official CLI for [Angular](https://angular.io/) capable of generating new projects, generating boilerplate files, and testing apps with LiveReload
  - name: '@angular/cli'
    bin: ng

  # @npm [@cloudflare/wrangler](https://npmjs.com/package/@cloudflare/wrangler) | [GitHub](https://github.com/cloudflare/wrangler) - A CLI tool designed for folks who are interested in using Cloudflare Workers
  - name: '@cloudflare/wrangler'
    bin: wrangler

  # @npm [@ionic/cli](https://npmjs.com/package/@ionic/cli) | [GitHub](https://github.com/ionic-team/ionic-cli) - A command line interface (CLI) is go-to tool for developing Ionic apps
  - name: '@ionic/cli'
    bin: ionic

  # @npm [@nestjs/cli](https://npmjs.com/package/@nestjs/cli) | [GitHub](https://github.com/nestjs/nest-cli) - A command-line interface tool that helps you to initialize, develop, and maintain your Nest applications
  - name: '@nestjs/cli'
    bin: nest

  # @npm [@sentry/cli](https://npmjs.com/package/@sentry/cli) | [GitHub](https://github.com/getsentry/sentry-cli) - A Sentry command line client for some generic tasks
  - name: '@sentry/cli'
    bin: sentry-cli

  # @npm [@vercel/ncc](https://npmjs.com/package/@vercel/ncc) | [GitHub](https://github.com/vercel/ncc) - CLI for compiling a Node.js module into a single file, together with all its dependencies, gcc-style
  - name: '@vercel/ncc'
    bin: ncc

  # @npm [auto-install](https://npmjs.com/package/auto-install) | [GitHub](https://github.com/siddharthkp/auto-install) - Auto installs dependencies as you code
  - name: auto-install
    bin: auto-install

  # @npm [bitly-cli-client](https://npmjs.com/package/bitly-cli-client) | [GitHub](https://github.com/xxczaki/bitly-cli-client) - Shorten links with Bitly in the terminal
  - name: bitly-cli-client
    bin: bitly

  # @npm [browser-sync](https://browsersync.io/) | [GitHub](https://github.com/BrowserSync/browser-sync) - Time-saving synchronized browser testing - test desktop and mobile versions of a website at the same time
  - name: browser-sync
    bin: browser-sync

  # @npm [caniuse-cmd](https://npmjs.com/package/caniuse-cmd) | [GitHub](https://github.com/sgentle/caniuse-cmd) - Caniuse command line tool
  - name: caniuse-cmd
    bin: caniuse

  # @npm [carbon-now-cli](https://npmjs.com/package/carbon-now-cli) | [GitHub](https://github.com/mixn/carbon-now-cli) - Tool that generates beautiful images of source code through an intuitive UI, while customizing aspects like fonts, themes, window controls and much mor
  - name: carbon-now-cli
    bin: carbon-now

  # @npm [commitizen](https://npmjs.com/package/commitizen) | [GitHub](https://github.com/commitizen/cz-cli) - The commitizen command line utility
  - name: commitizen
    bin: cz

  # @npm [cordova](https://npmjs.com/package/cordova) | [GitHub](https://github.com/apache/cordova-android) - The command line tool to build, deploy and manage Cordova-based applications
  - name: cordova
    bin: cordova

  # @npm [deviceframe](https://npmjs.com/package/deviceframe) | [GitHub](https://github.com/c0bra/deviceframe) - Put device frames around mobile/web/progressive app screenshots
  - name: deviceframe
    bin: dframe

  # @npm [editly](https://npmjs.com/package/editly) | [GitHub](https://github.com/mifi/editly) - A tool and framework for declarative NLE (non-linear video editing) using Node.js and ffmpeg
  - name: editly
    bin: editly

  # @npm [electron](https://npmjs.com/package/electron) | [GitHub](https://github.com/electron/electron-quick-start) - A tool that enables to write cross-platform desktop applications using JavaScript, HTML and CSS
  - name: electron
    bin: electron

  # @npm [emma-cli](https://npmjs.com/package/emma-cli) | [GitHub](https://github.com/maticzav/emma-cli) - Install the package you are looking for
  - name: emma-cli
    bin: emma

  # @npm [emoj](https://npmjs.com/package/emoj) | [GitHub](https://github.com/sindresorhus/emoj) - Find relevant emoji from text on the command-line
  - name: emoj
    bin: emoj

  # @npm [empty-trash-cli](https://npmjs.com/package/empty-trash-cli) | [GitHub](https://github.com/sindresorhus/empty-trash-cli) - A CLI to empty the trash
  - name: empty-trash-cli
    bin: empty-trash

  # @npm [eslint](https://npmjs.com/package/eslint) | [GitHub](https://github.com/eslint/eslint) - A tool for identifying and reporting on patterns found in ECMAScript/JavaScript code
  - name: eslint
    bin: eslint

  # @npm [fastify-cli](https://npmjs.com/package/fastify-cli) | [GitHub](https://github.com/fastify/fastify-cli) - Command line tools for Fastify. Generate, write, and run an application with one single command
  - name: fastify-cli
    bin: fastify

  # @npm [firebase-tools](https://npmjs.com/package/firebase-tools) | [GitHub](https://github.com/firebase/firebase-tools) - The Firebase Command Line Interface (CLI) Tools can be used to test, manage, and deploy Firebase project from the command line
  - name: firebase-tools
    bin: firebase

  # @npm [fkill-cli](https://npmjs.com/package/fkill-cli) | [GitHub](https://github.com/sindresorhus/fkill-cli) - Fabulously kill processes. Cross-platform.
  - name: fkill-cli
    bin: fkill

  # @npm [fx](https://npmjs.com/package/fx) | [GitHub](https://github.com/antonmedv/fx) - Command-line JSON processing tool
  - name: fx
    bin: fx

  # @npm [git-open](https://npmjs.com/package/git-open) | [GitHub](https://github.com/paulirish/git-open) - Type git open to open the repo website (GitHub, GitLab, Bitbucket) in browser
  - name: git-open

  # @npm [google-font-installer](https://npmjs.com/package/google-font-installer) | [GitHub](https://github.com/lordgiotto/google-font-installer) - Google Font Installer is a NodeJS module/CLI that lets you Search, Download and Install fonts offered by Google Web Fonts
  - name: google-font-installer
    bin: gfi

  # @npm [gtop](https://npmjs.com/package/gtop) | [GitHub](https://github.com/aksakalli/gtop) - System monitoring dashboard for terminal
  - name: gtop
    bin: gtop

  # @npm [gulp](https://npmjs.com/package/gulp) | [GitHub](https://github.com/gulpjs/gulp) - A toolkit that helps you automate painful or time-consuming tasks in your development workflow
  - name: gulp
    bin: gulp

  # @npm [imgur-uploader-cli](https://npmjs.com/package/imgur-uploader-cli) | [GitHub](https://github.com/kevva/imgur-uploader-cli) - CLI to upload images to imgur
  - name: imgur-uploader-cli
    bin: imgur-uploader

  # @npm [ios-deploy](https://npmjs.com/package/ios-deploy) | [GitHub](https://github.com/ios-control/ios-deploy) - Command line tool to install aand debug iOS apps
  - name: ios-deploy
    bin: ios-deploy
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @npm [ipfs-deploy](https://npmjs.com/package/ipfs-deploy) | [GitHub](https://github.com/ipfs-shipyard/ipfs-deploy) - Upload static website to IPFS pinning services and optionally update DNS
  - name: ipfs-deploy
    bin: ipd

  # @npm [is-up-cli](https://npmjs.com/package/is-up-cli) | [GitHub](https://github.com/sindresorhus/is-up-cli) - Check whether a website is up or down using the isitup.org API
  - name: is-up-cli
    bin: is-up

  # @npm [localtunnel](https://npmjs.com/package/localtunnel) | [GitHub](https://github.com/localtunnel/localtunnel) - localtunnel exposes localhost to the world for easy testing and sharing
  - name: localtunnel
    bin: localtunnel

  # @npm [mjml](https://npmjs.com/package/mjml) | [GitHub](https://github.com/mjmlio/mjml) - A markup language created by Mailjet and designed to reduce the pain of coding a responsive email
  - name: mjml
    bin: mjml

  # @npm [nativefier](https://npmjs.com/package/nativefier) | [GitHub](https://github.com/nativefier/nativefier) - Tool to make any web page a desktop application
  - name: nativefier
    bin: nativefier

  # @npm [nectarjs](https://npmjs.com/package/nectarjs) | [GitHub](https://github.com/nectarjs/nectarjs) - A JavaScript native compiler
  - name: nectarjs
    bin: nectar

  # @npm [newman](https://npmjs.com/package/newman) | [GitHub](https://github.com/postmanlabs/newman) - A command-line collection runner for Postman
  - name: newman
    bin: newman

  # @npm [np](https://npmjs.com/package/np) | [GitHub](https://github.com/sindresorhus/np) - A better npm publish
  - name: np
    bin: np

  # @npm [npm-check](https://npmjs.com/package/npm-check) | [GitHub](https://github.com/dylang/npm-check) - Check for outdated, incorrect, and unused dependencies
  - name: npm-check
    bin: npm-check

  # @npm [nrm](https://npmjs.com/package/nrm) | [GitHub](https://github.com/Pana/nrm) - nrm can help you easy and fast switch between different npm registries
  - name: nrm
    bin: nrm

  # @npm [oclif](https://npmjs.com/package/oclif) | [GitHub](https://github.com/oclif/oclif) - A framework for building CLIs in Node.js
  - name: oclif
    bin: oclif

  # @npm [package-size](https://npmjs.com/package/package-size) | [GitHub](https://github.com/egoist/package-size)  - Tool to get the bundle size of an npm package
  - name: package-size
    bin: package-size

  # @npm [pageres-cli](https://npmjs.com/package/pageres-cli) | [GitHub](https://github.com/sindresorhus/pageres-cli) - A CLI to capture screenshots of websites in various resolutions
  - name: pageres-cli
    bin: pageres

  # @npm [playwright](https://npmjs.com/package/playwright) | [GitHub](https://github.com/Microsoft/playwright) - Single API to automate Chromium, WebKit, and Firefox (available as a CLI and library)
  - name: playwright
    bin: playwright

  # @npm [pm2](https://npmjs.com/package/pm2) | [GitHub](https://github.com/Unitech/pm2) - PM2 is a production process manager for Node.js applications with a built-in load balancer
  - name: pm2
    bin: pm2

  # @npm [pkg](https://npmjs.com/package/pkg) | [GitHub](https://github.com/vercel/pkg) - This command line interface enables you to package your Node.js project into an executable that can be run even on devices without Node.js installed
  - name: pkg
    bin: pkg

  # @npm [prettier](https://npmjs.com/package/prettier) | [GitHub](https://github.com/prettier/prettier) - A code formatter
  - name: prettier
    bin: prettier

  # @npm [psi](https://npmjs.com/package/psi) | [GitHub](https://github.com/GoogleChromeLabs/psi) - PageSpeed Insights with reporting
  - name: psi
    bin: psi

  # @npm [ramda-cli](https://npmjs.com/package/ramda-cli) | [GitHub](https://github.com/raine/ramda-cli) - A tool for processing data with functional pipelines in the command-line or interactively in browser
  - name: ramda-cli
    bin: ramda

  # @npm [semantic-release](https://npmjs.com/package/semantic-release) | [GitHub](https://github.com/semantic-release/semantic-release) - A tool that automates the process of releasing software, featuring integrations with GitHub / GitLab releases
  - name: semantic-release
    bin: semantic-release

  # @npm [serve](https://npmjs.com/package/serve) | [GitHub](https://github.com/vercel/serve) - Static file serving and directory listing
  - name: serve
    bin: serve

  # @npm [serverless](https://npmjs.com/package/serverless) | [GitHub](https://github.com/serverless/serverless) - Serverless Framework â€“ Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more
  - name: serverless
    bin: serverless

  # @npm [share-cli](https://npmjs.com/package/share-cli) | [GitHub](https://github.com/marionebl/share-cli) - Quickly share files from your command line
  - name: share-cli
    bin: share

  # @npm [sharp-cli](https://npmjs.com/package/sharp-cli) | [GitHub](https://github.com/vseventer/sharp-cli) - CLI for sharp, a high performance Node.js image processing module
  - name: sharp-cli
    bin: sharp

  # @npm [speed-test](https://npmjs.com/package/speed-test) | [GitHub](https://github.com/sindresorhus/speed-test) - Test your internet connection speed and ping using speedtest.net from the CLI
  - name: speed-test
    bin: speed-test

  # @npm [stegcloak](https://npmjs.com/package/stegcloak) | [GitHub](https://github.com/KuroLabs/stegcloak) - StegCloak is a pure JavaScript steganography module designed in functional programming style, to hide secrets inside text by compressing and encrypting the secret before cloaking it with special unicode invisible characters
  - name: stegcloak
    bin: stegcloak

  # @npm [supdock](https://npmjs.com/package/supdock) | [GitHub](https://github.com/segersniels/supdock) - A CLI for running commands like "docker logs" in an easier, more interactive way
  - name: supdock
    bin: supdock

  # @npm [surge](https://npmjs.com/package/surge) | [GitHub](https://github.com/sintaxi/surge) - Publish web apps to a CDN with a single command and no setup required
  - name: surge
    bin: surge

  # @npm [svgo](https://npmjs.com/package/svgo) | [GitHub](https://github.com/svg/svgo) - SVG Optimizer is a Node.js-based tool for optimizing SVG vector graphics files
  - name: svgo
    bin: svgo

  # @npm [terminalizer](https://npmjs.com/package/terminalizer) | [GitHub](https://github.com/faressoft/terminalizer) - Record your terminal and generate animated gif images or share a web player link terminalizer.com
  - name: terminalizer
    bin: terminalizer

  # @npm [tinypng-cli](https://npmjs.com/package/tinypng-cli) | [GitHub](https://github.com/websperts/tinypng-cli) - Handy command line tool for shrinking PNG images using the TinyPNG API
  - name: tinypng-cli
    bin: tinypng

  # @npm [tldr](https://npmjs.com/package/tldr) | [GitHub](https://github.com/tldr-pages/tldr-node-client) - A Node.js based command-line client for tldr
  - name: tldr
    bin: tldr

  # @npm [ts2c](https://npmjs.com/package/ts2c) | [GitHub](https://github.com/andrei-markeev/ts2c) - A JavaScript/TypeScript to C compiler
  - name: ts2c
    bin: ts2c

  # @npm [typescript](https://npmjs.com/package/typescript) | [GitHub](https://github.com/Microsoft/TypeScript) - A language for application-scale JavaScript
  - name: typescript
    bin: tsc

  # @npm [wifi-password-cli](https://npmjs.com/package/wifi-password-cli) | [GitHub](https://github.com/kevva/wifi-password-cli) - CLI to get current wifi password
  - name: wifi-password-cli
    bin: wifi-password

  # @npm [wordpressify](https://npmjs.com/package/wordpressify) | [GitHub](https://github.com/luangjokaj/wordpressify) - Automate your WordPress development workflow
  - name: wordpressify
    bin: wordpressify

  # @npm [zx](https://npmjs.com/package/zx) | [GitHub](https://github.com/google/zx) - A tool for writing better scripts
  - name: zx
    bin: zx
