---
nodejs_npm_global_packages:
  # @npm [@angular/cli](https://npmjs.com/package/@angular/cli) - Official CLI for [Angular](https://angular.io/) capable of generating new projects, generating boilerplate files, and testing apps with LiveReload
  - name: "@angular/cli"

  # @npm [@cloudflare/wrangler](https://npmjs.com/package/@cloudflare/wrangler) - A CLI tool designed for folks who are interested in using Cloudflare Workers
  - name: "@cloudflare/wrangler"

  # @npm [@ionic/cli](https://npmjs.com/package/@ionic/cli) - A command line interface (CLI) is go-to tool for developing Ionic apps
  - name: "@ionic/cli"

  # @npm [@nestjs/cli](https://npmjs.com/package/@nestjs/cli) - A command-line interface tool that helps you to initialize, develop, and maintain your Nest applications
  - name: "@nestjs/cli"

  # @npm [@prettier/plugin-ruby](https://npmjs.com/package/@prettier/plugin-ruby) - A prettier plugin for the Ruby programming language and its ecosystem
  - name: "@prettier/plugin-ruby"

  # @npm [@prettier/plugin-xml](https://npmjs.com/package/@prettier/plugin-xml) - A prettier plugin for XML. prettier is an opinionated code formatter that supports multiple languages and integrates with most editors
  - name: "@prettier/plugin-xml"

  # @npm [@sentry/cli](https://npmjs.com/package/@sentry/cli) - A Sentry command line client for some generic tasks
  - name: "@sentry/cli"

  # @npm [@vercel/ncc](https://npmjs.com/package/@vercel/ncc) - CLI for compiling a Node.js module into a single file, together with all its dependencies, gcc-style
  - name: "@vercel/ncc"

  # @npm [add-gitignore](https://npmjs.com/package/add-gitignore) - CLI script that generates a .gitignore file for the projects
  - name: add-gitignore

  # @npm [auto-install](https://npmjs.com/package/auto-install) - Auto installs dependencies as you code
  - name: auto-install

  # @npm [bitly-cli-client](https://npmjs.com/package/bitly-cli-client) - Shorten links with Bitly in the terminal
  - name: bitly-cli-client

  # @npm [browser-sync](https://browsersync.io/) - Time-saving synchronized browser testing - test desktop and mobile versions of a website at the same time
  - name: browser-sync

  # @npm [caniuse-cmd](https://npmjs.com/package/caniuse-cmd) - Caniuse command line tool
  - name: caniuse-cmd

  # @npm [carbon-now-cli](https://npmjs.com/package/carbon-now-cli) - Tool that generates beautiful images of source code through an intuitive UI, while customizing aspects like fonts, themes, window controls and much mor
  - name: carbon-now-cli

  # @npm [commitizen](https://npmjs.com/package/commitizen) - The commitizen command line utility
  - name: commitizen

  # @npm [composerize](https://npmjs.com/package/composerize) - Turns docker run commands into docker-compose files
  - name: composerize

  # @npm [cordova](https://npmjs.com/package/cordova) - The command line tool to build, deploy and manage Cordova-based applications
  - name: cordova

  # @npm [deviceframe](https://npmjs.com/package/deviceframe) - Put device frames around mobile/web/progressive app screenshots
  - name: deviceframe

  # @npm [editly](https://npmjs.com/package/editly) - A tool and framework for declarative NLE (non-linear video editing) using Node.js and ffmpeg
  - name: editly

  # @npm [electron](https://npmjs.com/package/electron) - A tool that enables to write cross-platform desktop applications using JavaScript, HTML and CSS
  - name: electron

  # @npm [emma-cli](https://npmjs.com/package/emma-cli) - Install the package you are looking for
  - name: emma-cli

  # @npm [emoj](https://npmjs.com/package/emoj) - Find relevant emoji from text on the command-line
  - name: emoj

  # @npm [empty-trash-cli](https://npmjs.com/package/empty-trash-cli) - A CLI to empty the trash
  - name: empty-trash-cli

  # @npm [eslint](https://npmjs.com/package/eslint) - A tool for identifying and reporting on patterns found in ECMAScript/JavaScript code
  - name: eslint

  # @npm [fastify-cli](https://npmjs.com/package/fastify-cli) - Command line tools for Fastify. Generate, write, and run an application with one single command
  - name: fastify-cli

  # @npm [firebase-tools](https://npmjs.com/package/firebase-tools) - The Firebase Command Line Interface (CLI) Tools can be used to test, manage, and deploy Firebase project from the command line
  - name: firebase-tools

  # @npm [firetable](https://npmjs.com/package/firetable) - The Firetable CLI automates the steps required to set up the Firetable app and other operations on computer
  - name: firetable

  # @npm [fkill-cli](https://npmjs.com/package/fkill-cli) - Fabulously kill processes. Cross-platform.
  - name: fkill-cli

  # @npm [fx](https://npmjs.com/package/fx) - Command-line JSON processing tool
  - name: fx

  # @npm [gistup](https://npmjs.com/package/gistup) - Create a gist from the command line
  - name: gistup

  # @npm [git-open](https://npmjs.com/package/git-open) - Type git open to open the repo website (GitHub, GitLab, Bitbucket) in browser
  - name: git-open

  # @npm [git-standup](https://npmjs.com/package/git-standup) - Shows commits from the last working day in the current directory and the directories below current level plus it comes with several options to modify how it behaves
  - name: git-standup

  # @npm [google-font-installer](https://npmjs.com/package/google-font-installer) - Google Font Installer is a NodeJS module/CLI that lets you Search, Download and Install fonts offered by Google Web Fonts
  - name: google-font-installer

  # @npm [gtop](https://npmjs.com/package/gtop) - System monitoring dashboard for terminal
  - name: gtop

  # @npm [gulp](https://npmjs.com/package/gulp) - A toolkit that helps you automate painful or time-consuming tasks in your development workflow
  - name: gulp

  # @npm [imgur-uploader-cli](https://npmjs.com/package/imgur-uploader-cli) - CLI to upload images to imgur
  - name: imgur-uploader-cli

  # @npm [ios-deploy](https://npmjs.com/package/ios-deploy) - Command line tool to install aand debug iOS apps
  - name: ios-deploy
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @npm [ipfs-deploy](https://npmjs.com/package/ipfs-deploy) - Upload static website to IPFS pinning services and optionally update DNS
  - name: ipfs-deploy

  # @npm [is-up-cli](https://npmjs.com/package/is-up-cli) - Check whether a website is up or down using the isitup.org API
  - name: is-up-cli

  # @npm [jp-cli](https://npmjs.com/package/jp-cli) - Simply parse JSON from any input source
  - name: jp-cli

  # @npm [jsfmt](https://npmjs.com/package/jsfmt) - For formatting, searching, and rewriting JavaScript. Analogous to gofmt
  - name: jsfmt

  # @npm [localtunnel](https://npmjs.com/package/localtunnel) - localtunnel exposes localhost to the world for easy testing and sharing
  - name: localtunnel

  # @npm [mjml](https://npmjs.com/package/mjml) - A markup language created by Mailjet and designed to reduce the pain of coding a responsive email
  - name: mjml

  # @npm [mklicense](https://npmjs.com/package/mklicense) - CLI tool for generating Licenses
  - name: mklicense

  # @npm [movie-cli](https://npmjs.com/package/movie-cli) - A CLI for getting information about a movies and comparing two movies
  - name: movie-cli

  # @npm [nativefier](https://npmjs.com/package/nativefier) - Tool to make any web page a desktop application
  - name: nativefier

  # @npm [navi](https://npmjs.com/package/navi) - A JavaScript library for declaratively mapping URLs to asynchronous content
  - name: navi

  # @npm [nectarjs](https://npmjs.com/package/nectarjs) - A JavaScript native compiler
  - name: nectarjs

  # @npm [newman](https://npmjs.com/package/newman) - A command-line collection runner for Postman
  - name: newman

  # @npm [np](https://npmjs.com/package/np) - A better npm publish
  - name: np

  # @npm [npm-check](https://npmjs.com/package/npm-check) - Check for outdated, incorrect, and unused dependencies
  - name: npm-check

  # @npm [nrm](https://npmjs.com/package/nrm) - nrm can help you easy and fast switch between different npm registries
  - name: nrm

  # @npm [nve](https://npmjs.com/package/nve) - Run any command on specific Node.js versions
  - name: nve

  # @npm [oclif](https://npmjs.com/package/oclif) - A framework for building CLIs in Node.js
  - name: oclif

  # @npm [package-size](https://npmjs.com/package/package-size) - Tool to get the bundle size of an npm package
  - name: package-size

  # @npm [pageres-cli](https://npmjs.com/package/pageres-cli) - A CLI to capture screenshots of websites in various resolutions
  - name: pageres-cli

  # @npm [playwright](https://npmjs.com/package/playwright) - Single API to automate Chromium, WebKit, and Firefox (available as a CLI and library)
  - name: playwright

  # @npm [pm2](https://npmjs.com/package/pm2) - PM2 is a production process manager for Node.js applications with a built-in load balancer
  - name: pm2

  # @npm [pxi](https://npmjs.com/package/pxi) - pxi (pixie) is a small, fast, and magical command-line data processor similar to jq, mlr, and awk
  - name: pxi

  # @npm [pkg](https://npmjs.com/package/pkg) - This command line interface enables you to package your Node.js project into an executable that can be run even on devices without Node.js installed
  - name: pkg

  # @npm [prettier](https://npmjs.com/package/prettier) - A code formatter
  - name: prettier

  # @npm [prettier-package-json](https://npmjs.com/package/prettier-package-json) - A JSON formatter inspired by prettier
  - name: prettier-package-json

  # @npm [prettier-plugin-go-template](https://npmjs.com/package/prettier-plugin-go-template) - Tool to fix formatting for go template files
  - name: prettier-plugin-go-template

  # @npm [prettier-plugin-java](https://npmjs.com/package/prettier-plugin-java) - An opinionated code formatter which forces a certain coding style
  - name: prettier-plugin-java

  # @npm [prettier-plugin-properties](https://npmjs.com/package/prettier-plugin-properties) - Adds support to Prettier for .properties files
  - name: prettier-plugin-properties

  # @npm [prettier-plugin-sh](https://npmjs.com/package/prettier-plugin-sh) - Prettier is an opinionated code formatter
  - name: prettier-plugin-sh

  # @npm [prettier-plugin-toml](https://npmjs.com/package/prettier-plugin-toml) - Prettier is an opinionated code formatter
  - name: prettier-plugin-toml

  # @npm [psi](https://npmjs.com/package/psi) - PageSpeed Insights with reporting
  - name: psi

  # @npm [serve](https://npmjs.com/package/serve) - Static file serving and directory listing
  - name: serve

  # @npm [serverless](https://npmjs.com/package/serverless) - Serverless Framework â€“ Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more
  - name: serverless

  # @npm [share-cli](https://npmjs.com/package/share-cli) - Quickly share files from your command line
  - name: share-cli

  # @npm [sharp-cli](https://npmjs.com/package/sharp-cli) - CLI for sharp, a high performance Node.js image processing module
  - name: sharp-cli

  # @npm [speed-test](https://npmjs.com/package/speed-test) - Test your internet connection speed and ping using speedtest.net from the CLI
  - name: speed-test

  # @npm [stegcloak](https://npmjs.com/package/stegcloak) - StegCloak is a pure JavaScript steganography module designed in functional programming style, to hide secrets inside text by compressing and encrypting the secret before cloaking it with special unicode invisible characters
  - name: stegcloak

  # @npm [surge](https://npmjs.com/package/surge) - Publish web apps to a CDN with a single command and no setup required
  - name: surge

  # @npm [svgo](https://npmjs.com/package/svgo) - SVG Optimizer is a Node.js-based tool for optimizing SVG vector graphics files
  - name: svgo

  # @npm [terminalizer](https://npmjs.com/package/terminalizer) - Record your terminal and generate animated gif images or share a web player link terminalizer.com
  - name: terminalizer

  # @npm [tinypng-cli](https://npmjs.com/package/tinypng-cli) - Handy command line tool for shrinking PNG images using the TinyPNG API
  - name: tinypng-cli

  # @npm [tldr](https://npmjs.com/package/tldr) - A Node.js based command-line client for tldr
  - name: tldr

  # @npm [typescript](https://npmjs.com/package/typescript) - A language for application-scale JavaScript
  - name: typescript

  # @npm [wallace-cli](https://npmjs.com/package/wallace-cli) - Pretty CSS analytics in terminal
  - name: wallace-cli

  # @npm [wifi-password-cli](https://npmjs.com/package/wifi-password-cli) - CLI to get current wifi password
  - name: wifi-password-cli

  # @npm [wordpressify](https://npmjs.com/package/wordpressify) - Automate your WordPress development workflow
  - name: wordpressify

  # @npm [zx](https://npmjs.com/package/zx) - A tool for writing better scripts
  - name: zx
