---
nodejs_npm_global_packages:

  # @action NPM Packages # [@angular/cli](https://npmjs.com/package/@angular/cli)
  # Official CLI for [Angular](https://angular.io/) capable of generating new projects, generating boilerplate files, and testing apps with LiveReload
  - name: "@angular/cli"

  # @action NPM Packages # [@cloudflare/wrangler](https://npmjs.com/package/@cloudflare/wrangler)
  # A CLI tool designed for folks who are interested in using Cloudflare Workers
  - name: "@cloudflare/wrangler"

  # @action NPM Packages # [@ionic/cli](https://npmjs.com/package/@ionic/cli)
  # A command line interface (CLI) is go-to tool for developing Ionic apps
  - name: "@ionic/cli"

  # @action NPM Packages # [@nestjs/cli](https://npmjs.com/package/@nestjs/cli)
  # A command-line interface tool that helps you to initialize, develop, and maintain your Nest applications
  - name: "@nestjs/cli"

  # @action NPM Packages # [@prettier/plugin-php](https://npmjs.com/package/@prettier/plugin-php)
  # An opinionated code formatter
  - name: "@prettier/plugin-php"

  # @action NPM Packages # [@prettier/plugin-ruby](https://npmjs.com/package/@prettier/plugin-ruby)
  # A prettier plugin for the Ruby programming language and its ecosystem
  - name: "@prettier/plugin-ruby"

  # @action NPM Packages # [@prettier/plugin-xml](https://npmjs.com/package/@prettier/plugin-xml)
  # A prettier plugin for XML. prettier is an opinionated code formatter that supports multiple languages and integrates with most editors
  - name: "@prettier/plugin-xml"

  # @action NPM Packages # [@sentry/cli](https://npmjs.com/package/@sentry/cli)
  # A Sentry command line client for some generic tasks
  - name: "@sentry/cli"

  # @action NPM Packages # [@vercel/ncc](https://npmjs.com/package/@vercel/ncc)
  # CLI for compiling a Node.js module into a single file, together with all its dependencies, gcc-style
  - name: "@vercel/ncc"

  # @action NPM Packages # [add-gitignore](https://npmjs.com/package/add-gitignore)
  # CLI script that generates a .gitignore file for the projects
  - name: add-gitignore

  # @action NPM Packages # [auto-install](https://npmjs.com/package/auto-install)
  # Auto installs dependencies as you code
  - name: auto-install

  # @action NPM Packages # [bitly-cli-client](https://npmjs.com/package/bitly-cli-client)
  # Shorten links with Bitly in the terminal
  - name: bitly-cli-client

  # @action NPM Packages # [caniuse-cmd](https://npmjs.com/package/caniuse-cmd)
  # Caniuse command line tool
  - name: caniuse-cmd

  # @action NPM Packages # [carbon-now-cli](https://npmjs.com/package/carbon-now-cli)
  # Tool that generates beautiful images of source code through an intuitive UI, while customizing aspects like fonts, themes, window controls and much mor
  - name: carbon-now-cli

  # @action NPM Packages # [commitizen](https://npmjs.com/package/commitizen)
  # The commitizen command line utility
  - name: commitizen

  # @action NPM Packages # [composerize](https://npmjs.com/package/composerize)
  # Turns docker run commands into docker-compose files
  - name: composerize

  # @action NPM Packages # [cordova](https://npmjs.com/package/cordova)
  # The command line tool to build, deploy and manage Cordova-based applications
  - name: cordova

  # @action NPM Packages # [deviceframe](https://npmjs.com/package/deviceframe)
  # Put device frames around mobile/web/progressive app screenshots
  - name: deviceframe

  # @action NPM Packages # [editly](https://npmjs.com/package/editly)
  # A tool and framework for declarative NLE (non-linear video editing) using Node.js and ffmpeg
  - name: editly

  # @action NPM Packages # [electron](https://npmjs.com/package/electron)
  # A tool that enables to write cross-platform desktop applications using JavaScript, HTML and CSS
  - name: electron

  # @action NPM Packages # [emma-cli](https://npmjs.com/package/emma-cli)
  # Install the package you are looking for
  - name: emma-cli

  # @action NPM Packages # [emoj](https://npmjs.com/package/emoj)
  # Find relevant emoji from text on the command-line
  - name: emoj

  # @action NPM Packages # [empty-trash-cli](https://npmjs.com/package/empty-trash-cli)
  # A CLI to empty the trash
  - name: empty-trash-cli

  # @action NPM Packages # [eslint](https://npmjs.com/package/eslint)
  # A tool for identifying and reporting on patterns found in ECMAScript/JavaScript code
  - name: eslint

  # @action NPM Packages # [fastify-cli](https://npmjs.com/package/fastify-cli)
  # Command line tools for Fastify. Generate, write, and run an application with one single command
  - name: fastify-cli

  # @action NPM Packages # [firebase-tools](https://npmjs.com/package/firebase-tools)
  # The Firebase Command Line Interface (CLI) Tools can be used to test, manage, and deploy Firebase project from the command line
  - name: firebase-tools

  # @action NPM Packages # [firetable](https://npmjs.com/package/firetable)
  # The Firetable CLI automates the steps required to set up the Firetable app and other operations on computer
  - name: firetable

  # @action NPM Packages # [fkill-cli](https://npmjs.com/package/fkill-cli)
  # Fabulously kill processes. Cross-platform.
  - name: fkill-cli

  # @action NPM Packages # [fx](https://npmjs.com/package/fx)
  # Command-line JSON processing tool
  - name: fx

  # @action NPM Packages # [gistup](https://npmjs.com/package/gistup)
  # Create a gist from the command line
  - name: gistup

  # @action NPM Packages # [git-open](https://npmjs.com/package/git-open)
  # Type git open to open the repo website (GitHub, GitLab, Bitbucket) in browser
  - name: git-open

  # @action NPM Packages # [git-standup](https://npmjs.com/package/git-standup)
  # Shows commits from the last working day in the current directory and the directories below current level plus it comes with several options to modify how it behaves
  - name: git-standup

  # @action NPM Packages # [google-font-installer](https://npmjs.com/package/google-font-installer)
  # Google Font Installer is a NodeJS module/CLI that lets you Search, Download and Install fonts offered by Google Web Fonts
  - name: google-font-installer

  # @action NPM Packages # [gtop](https://npmjs.com/package/gtop)
  # System monitoring dashboard for terminal
  - name: gtop

  # @action NPM Packages # [gulp](https://npmjs.com/package/gulp)
  # A toolkit that helps you automate painful or time-consuming tasks in your development workflow
  - name: gulp

  # @action NPM Packages # [imgur-uploader-cli](https://npmjs.com/package/imgur-uploader-cli)
  # CLI to upload images to imgur
  - name: imgur-uploader-cli

  # @action NPM Packages # [ios-deploy](https://npmjs.com/package/ios-deploy)
  # Command line tool to install aand debug iOS apps
  - name: ios-deploy
    when: "{{ ansible_os_family == 'Darwin' }}"

  # @action NPM Packages # [ipfs-deploy](https://npmjs.com/package/ipfs-deploy)
  # Upload static website to IPFS pinning services and optionally update DNS
  - name: ipfs-deploy

  # @action NPM Packages # [is-up-cli](https://npmjs.com/package/is-up-cli)
  # Check whether a website is up or down using the isitup.org API
  - name: is-up-cli

  # @action NPM Packages # [jp-cli](https://npmjs.com/package/jp-cli)
  # Simply parse JSON from any input source
  - name: jp-cli

  # @action NPM Packages # [jsfmt](https://npmjs.com/package/jsfmt)
  # For formatting, searching, and rewriting JavaScript. Analogous to gofmt
  - name: jsfmt

  # @action NPM Packages # [localtunnel](https://npmjs.com/package/localtunnel)
  # localtunnel exposes localhost to the world for easy testing and sharing
  - name: localtunnel

  # @action NPM Packages # [mjml](https://npmjs.com/package/mjml)
  # A markup language created by Mailjet and designed to reduce the pain of coding a responsive email
  - name: mjml

  # @action NPM Packages # [mklicense](https://npmjs.com/package/mklicense)
  # CLI tool for generating Licenses
  - name: mklicense

  # @action NPM Packages # [movie-cli](https://npmjs.com/package/movie-cli)
  # A CLI for getting information about a movies and comparing two movies
  - name: movie-cli

  # @action NPM Packages # [nativefier](https://npmjs.com/package/nativefier)
  # Tool to make any web page a desktop application
  - name: nativefier

  # @action NPM Packages # [navi](https://npmjs.com/package/navi)
  # A JavaScript library for declaratively mapping URLs to asynchronous content
  - name: navi

  # @action NPM Packages # [nectarjs](https://npmjs.com/package/nectarjs)
  # A JavaScript native compiler
  - name: nectarjs

  # @action NPM Packages # [newman](https://npmjs.com/package/newman)
  # A command-line collection runner for Postman
  - name: newman

  # @action NPM Packages # [np](https://npmjs.com/package/np)
  # A better npm publish
  - name: np

  # @action NPM Packages # [npm-check](https://npmjs.com/package/npm-check)
  # Check for outdated, incorrect, and unused dependencies
  - name: npm-check

  # @action NPM Packages # [nrm](https://npmjs.com/package/nrm)
  # nrm can help you easy and fast switch between different npm registries
  - name: nrm

  # @action NPM Packages # [nve](https://npmjs.com/package/nve)
  # Run any command on specific Node.js versions
  - name: nve

  # @action NPM Packages # [oclif](https://npmjs.com/package/oclif)
  # A framework for building CLIs in Node.js
  - name: oclif

  # @action NPM Packages # [package-size](https://npmjs.com/package/package-size)
  # Tool to get the bundle size of an npm package
  - name: package-size

  # @action NPM Packages # [pageres-cli](https://npmjs.com/package/pageres-cli)
  # A CLI to capture screenshots of websites in various resolutions
  - name: pageres-cli

  # @action NPM Packages # [pm2](https://npmjs.com/package/pm2)
  # PM2 is a production process manager for Node.js applications with a built-in load balancer
  - name: pm2

  # @action NPM Packages # [pxi](https://npmjs.com/package/pxi)
  # pxi (pixie) is a small, fast, and magical command-line data processor similar to jq, mlr, and awk
  - name: pxi

  # @action NPM Packages # [pkg](https://npmjs.com/package/pkg)
  # This command line interface enables you to package your Node.js project into an executable that can be run even on devices without Node.js installed
  - name: pkg

  # @action NPM Packages # [prettier](https://npmjs.com/package/prettier)
  # A code formatter
  - name: prettier

  # @action NPM Packages # [prettier-package-json](https://npmjs.com/package/prettier-package-json)
  # A JSON formatter inspired by prettier
  - name: prettier-package-json

  # @action NPM Packages # [prettier-plugin-go-template](https://npmjs.com/package/prettier-plugin-go-template)
  # Tool to fix formatting for go template files
  - name: prettier-plugin-go-template

  # @action NPM Packages # [prettier-plugin-java](https://npmjs.com/package/prettier-plugin-java)
  # An opinionated code formatter which forces a certain coding style
  - name: prettier-plugin-java

  # @action NPM Packages # [prettier-plugin-properties](https://npmjs.com/package/prettier-plugin-properties)
  # Adds support to Prettier for .properties files
  - name: prettier-plugin-properties

  # @action NPM Packages # [prettier-plugin-sh](https://npmjs.com/package/prettier-plugin-sh)
  # Prettier is an opinionated code formatter
  - name: prettier-plugin-sh

  # @action NPM Packages # [prettier-plugin-toml](https://npmjs.com/package/prettier-plugin-toml)
  # Prettier is an opinionated code formatter
  - name: prettier-plugin-toml

  # @action NPM Packages # [psi](https://npmjs.com/package/psi)
  # PageSpeed Insights with reporting
  - name: psi

  # @action NPM Packages # [serve](https://npmjs.com/package/serve)
  # Static file serving and directory listing
  - name: serve

  # @action NPM Packages # [serverless](https://npmjs.com/package/serverless)
  # Serverless Framework â€“ Build web, mobile and IoT applications with serverless architectures using AWS Lambda, Azure Functions, Google CloudFunctions & more
  - name: serverless

  # @action NPM Packages # [share-cli](https://npmjs.com/package/share-cli)
  # Quickly share files from your command line
  - name: share-cli

  # @action NPM Packages # [sharp-cli](https://npmjs.com/package/sharp-cli)
  # CLI for sharp, a high performance Node.js image processing module
  - name: sharp-cli

  # @action NPM Packages # [speed-test](https://npmjs.com/package/speed-test)
  # Test your internet connection speed and ping using speedtest.net from the CLI
  - name: speed-test

  # @action NPM Packages # [stegcloak](https://npmjs.com/package/stegcloak)
  # StegCloak is a pure JavaScript steganography module designed in functional programming style, to hide secrets inside text by compressing and encrypting the secret before cloaking it with special unicode invisible characters
  - name: stegcloak

  # @action NPM Packages # [surge](https://npmjs.com/package/surge)
  # Publish web apps to a CDN with a single command and no setup required
  - name: surge

  # @action NPM Packages # [svgo](https://npmjs.com/package/svgo)
  # SVG Optimizer is a Node.js-based tool for optimizing SVG vector graphics files
  - name: svgo

  # @action NPM Packages # [taskbook](https://npmjs.com/package/taskbook)
  # Tasks, boards & notes for the command-line habitat
  - name: taskbook

  # @action NPM Packages # [terminalizer](https://npmjs.com/package/terminalizer)
  # Record your terminal and generate animated gif images or share a web player link terminalizer.com
  - name: terminalizer

  # @action NPM Packages # [tinypng-cli](https://npmjs.com/package/tinypng-cli)
  # Handy command line tool for shrinking PNG images using the TinyPNG API
  - name: tinypng-cli

  # @action NPM Packages # [tldr](https://npmjs.com/package/tldr)
  # A Node.js based command-line client for tldr
  - name: tldr

  # @action NPM Packages # [typescript](https://npmjs.com/package/typescript)
  # A language for application-scale JavaScript
  - name: typescript

  # @action NPM Packages # [wallace-cli](https://npmjs.com/package/wallace-cli)
  # Pretty CSS analytics in terminal
  - name: wallace-cli

  # @action NPM Packages # [wifi-password-cli](https://npmjs.com/package/wifi-password-cli)
  # CLI to get current wifi password
  - name: wifi-password-cli

  # @action NPM Packages # [wordpressify](https://npmjs.com/package/wordpressify)
  # Automate your WordPress development workflow
  - name: wordpressify

  # @action NPM Packages # [zx](https://npmjs.com/package/zx)
  # A tool for writing better scripts
  - name: zx
