---
# These are the pip packages that are automatically installed on hosts in the desktop group
pip_packages:
  # @action Python Packages # [ansible-lint](https://pypi.org/project/ansible-lint/)
  # Lint tool that checks [Ansible](https://www.ansible.com/) projects for best practices and problematic code
  - name: ansible-lint

  # @action Python Packages # [asciinema](https://pypi.org/project/asciinema/)
  # Tool that records terminal session and replay them in a terminal as well as in a web browser
  - name: asciinema

  # @action Python Packages # [aws-shell](https://pypi.org/project/aws-shell/)
  # AWS shell is the interactive productivity booster for the AWS CLI
  - name: aws-shell

  # @action Python Packages # [cookiecutter](https://pypi.org/project/cookiecutter/)
  # A command-line utility that creates projects from cookiecutters (project templates)
  - name: cookiecutter

  # @action Python Packages # [get-port-cli](https://pypi.org/project/get-port-cli/)
  # A tool to get an available port
  - name: get-port-cli

  # @action Python Packages # [gixy](https://pypi.org/project/gixy/)
  # A tool to analyze Nginx configuration
  - name: gixy

  # @action Python Packages # [httpstat](https://pypi.org/project/httpstat/)
  # A script that reflects curl statistics in a fascinating and well-defined way, it is a single file which is compatible with Python 3 and requires no additional software (dependencies) to be installed on a users system
  - name: httpstat

  # @action Python Packages # [http-prompt](https://pypi.org/project/http-prompt/)
  # An interactive command-line HTTP client featuring autocomplete and syntax highlighting, built on HTTPie and prompt_toolkit
  - name: http-prompt

  # @action Python Packages # [iredis](https://pypi.org/project/iredis/)
  # A terminal client for redis with auto-completion and syntax highlighting
  - name: iredis

  # @action Python Packages # [kube-shell](https://pypi.org/project/kube-shell/)
  # An integrated shell for working with the Kubernetes CLI
  - name: kube-shell

  # @action Python Packages # [litecli](https://pypi.org/project/litecli/)
  # A command-line client for SQLite databases that has auto-completion and syntax highlighting
  - name: litecli

  # @action Python Packages # [locust](https://pypi.org/project/locust/)
  # An easy to use,  scriptable and scalable performance testing tool
  - name: locust

  # @action Python Packages # [netaddr](https://pypi.org/project/netaddr/)
  # A system-independent network address manipulation library for Python 2.7 and 3.5+
  - name: netaddr

  # @action Python Packages # [ngxtop](https://pypi.org/project/ngxtop/)
  # ngxtop parses your nginx access log and outputs useful, top-like, metrics of your nginx server
  - name: ngxtop

  # @action Python Packages # [molecule](https://pypi.org/project/molecule/)
  # Molecule project is designed to aid in the development and testing of Ansible roles. Molecule provides support for testing with multiple instances, operating systems and distributions, virtualization providers, test frameworks and testing scenarios
  - name: molecule

  # @action Python Packages # [mycli](https://pypi.org/project/mycli/)
  # Command line interface for MySQL database with auto-completion and syntax highlighting
  - name: mycli

  # @action Python Packages # [pre-commit](https://pypi.org/project/pre-commit/)
  # A framework for managing and maintaining multi-language pre-commit hooks
  - name: pre-commit

  # @action Python Packages # [pywhat](https://pypi.org/project/pywhat/)
  # A tool that identify what something is, whether it be a file or a text, or even the hex of a file, and text within files - what is recursive
  - name: pywhat

  # @action Python Packages # [social-analyzer](https://pypi.org/project/social-analyzer/)
  # API, CLI & Web App for analyzing & finding a personâ€™s profile across social media websites
  - name: social-analyzer

  # @action Python Packages # [spotdl](https://pypi.org/project/spotdl/)
  # A tool to download Spotify playlists and songs along with album art and metadata
  - name: spotdl

  # @action Python Packages # [starred](https://pypi.org/project/starred/)
  # A tuple (or list) on the left side of a simple assignment (unpacking is not defined for augmented assignment) may contain at most one expression prepended with a single asterisk (which is henceforth called a "starred" expression, while the other expressions in the list are called "mandatory")
  - name: starred

  # @action Python Packages # [statcode](https://pypi.org/project/statcode/)
  # `man` pages for HTTP status codes (used by running `statcode 418`, for instance)
  - name: statcode

  # @action Python Packages # [truffleHog](https://pypi.org/project/truffleHog/)
  # A tool which makes it easier to search through the history of a git repository to discover passwords and other secrets
  - name: truffleHog

  # @action Python Packages # [virtualenv](https://pypi.org/project/virtualenv/)
  # A tool for creating isolated virtual python environments
  - name: virtualenv

  # @action Python Packages # [wpscan](https://pypi.org/project/wpscan/)
  # A simple Wordpress scanner written in python based on the work of WPScan
  - name: wpscan

  # @action Python Packages # [yamllint](https://pypi.org/project/yamllint/)
  # A linter for YAML files
  - name: yamllint
