---
# When set to true, ssh-keyscan will be performed on all the other clients
add_known_hosts: true

default_browser: brave

nodejs_npm_global_packages:
  - name: "@angular/cli"
  - name: "@ionic/cli"
  - name: "@nestjs/cli"
  - name: add-gitignore
  - name: auto-install
  - name: bitly-cli-client
  - name: caniuse-cmd
  - name: carbon-now-cli
  - name: commitizen
  - name: cordova
  - name: deviceframe # TODO: Address permissions error
  - name: electron # TODO: Address permissions error
  - name: empty-trash-cli
  - name: eslint
  - name: firebase-tools
  - name: fkill-cli
  - name: gistup
  - name: git-standup
  - name: gtop
  - name: gulp
  - name: imgur-uploader-cli # Source: https://github.com/kevva/imgur-uploader-cli
  - name: ionic
  - name: is-up-cli
  - name: localtunnel
  - name: mklicense
  - name: navi
  - name: normit # Source: https://github.com/pawurb/normit # TODO: Speech synthesis
  - name: np
  - name: readme-md-generator # Source: https://github.com/kefranabg/readme-md-generator
  - name: pageres-cli
  - name: serve # Source: https://github.com/vercel/serve
  - name: share-cli # Source: https://github.com/marionebl/share-cli
  - name: speed-test # Source: https://github.com/sindresorhus/speed-test
  - name: stegcloak # Allows you to add an encrypted, hidden phrase in any text string (works by using invisible characters)
  - name: surge
  - name: terminalizer # Record terminal as an animated GIF (https://github.com/faressoft/terminalizer)
  - name: tldr
  - name: typescript
  - name: wifi-password-cli

pip_packages:
  - name: ansible-lint # Recommends coding style changes for Ansible
  - name: aws-shell # CLI for AWS CLI that includes auto-completion (https://github.com/awslabs/aws-shell)
  - name: iredis # CLI for Redis which includes auto-completion and syntax highlighting (https://github.com/laixintao/iredis)
  - name: kube-shell # CLI for kubectl that includes auto-completion and syntax highlighting (https://github.com/cloudnativelabs/kube-shell)
  - name: litecli # CLI for SQLite that includes auto-completion and syntax highlighting (https://github.com/dbcli/litecli)
  - name: locust # Web performance benchmarking tool with UI
  - name: netaddr # Used for ipaddr filter on Ansible
  - name: molecule # Used for testing Ansible roles
  - name: mycli # CLI for MySQL that includes auto-completion and syntax highlighting (https://github.com/dbcli/mycli)
  - name: pgcli # CLI for Postgres that includes auto-completion and syntax highlighting (https://github.com/dbcli/pgcli)
  - name: pre-commit # Runs tasks before committing changes
  - name: yamllint # Lints .yml files

ruby_gems:
  - name: mdl # Markdown file linter - Source: https://github.com/markdownlint/markdownlint

vpn_connections:
  - file: Mullvad OpenVPN Denver (UDP 53).ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN Hong Kong.ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN Italy.ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN NYC.ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN Secaucus (TCP 80).ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard Germany (Custom Port).nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard Italy Brazil.nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard NYC (Custom Port).nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard NYC.nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard Switzerland.nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: NordVPN OpenVPN Texas.ovpn
    password: "{{ nordvpn_password }}"
    username: "{{ nordvpn_username }}"

vscode_extensions:
  - CoenraadS.bracket-pair-colorizer
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - ericadamski.carbon-now-sh
  - firefox-devtools.vscode-firefox-debug
  - googlecloudtools.cloudcode # Missing from code server
  - golang.Go
  - IBM.output-colorizer
  - msjsdiag.debugger-for-chrome
  - msjsdiag.debugger-for-edge
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-vscode-remote.remote-containers # Missing from code server
  - ms-vscode-remote.remote-ssh # Missing from code server
  - ms-vscode-remote.remote-wsl # Missing from code server
  - ms-python.python
  - ms-vscode.PowerShell
  - ms-vscode.vscode-typescript-tslint-plugin
  - MS-vsliveshare.vsliveshare # Missing from code server
  - pnp.polacode
  - redhat.vscode-yaml # New
  - richie5um2.vscode-sort-json # New
  - streetsidesoftware.code-spell-checker # New
  - tyriar.sort-lines # New
  - VisualStudioExptTeam.vscodeintellicode # Missing from code server
  - vscode-icons-team.vscode-icons
  - vsciot-vscode.vscode-arduino
  - vscoss.vscode-ansible
