---
# When set to true, ssh-keyscan will be performed on all the other clients
add_known_hosts: true

software:
  - altair
  - askgit
  - bat
  - bandwhich
  - betwixt
  - bitwarden
  - boilr
  - cerebro
  - consul-cli
  - croc
  - ctop
  - cumulus
  - dat
  - dat-desktop
  - delta
  - desed
  - deta
  - direnv
  - dive
  - docker-slim
  - dockle
  - doctl
  - dog
  - duf
  - dust
  - envconsul
  - fd
  - felony
  - ffsend
  - filebrowser
  - fselect
  - fuego
  - g-assist
  - ganache
  - glab
  - gitify
  - gitleaks
  - gitomatic
  - glab
  - glow
  - go-chromecast
  - gping
  - grex
  - gron
  - hclq
  - hexyl
  - hostctl
  - htmlq
  - hyperfine
  - jitsi-meet-electron
  - jo
  - jq
  - kdash # TODO - replace with k9s
  - kubenav
  - linuxkit
  - manta
  - mark-text
  - masscode
  - mc
  - mkcert
  - mockoon
  - motrix
  - mqttx
  - muffet
  - mullvad-vpn
  - nnn
  - nomino
  - nuclear
  - osquery
  - ots
  - oq
  - pastel
  - peco
  - pony
  - pretzel
  - procs
  - psu
  - pup
  - q
  - responsively
  - rip
  - runjs
  - s5cmd
  - schema
  - scrcpy
  - sd
  - shfmt
  - skm
  - snitch
  - sqlectron
  - ssh-vault
  - ssl-proxy
  - switchhosts
  - sysbench
  - tabby
  - task
  - teleport
  - tflint
  - temps
  - tokei
  - trivy
  - udemy-downloader-gui
  - webtorrent
  - wkhtmltopdf
  - xurls
  - yq

chromium_extensions:
  - name: 30 Seconds of Knowledge
    link: https://chrome.google.com/webstore/detail/30-seconds-of-knowledge/mmgplondnjekobonklacmemikcnhklla/related
  - name: AdGuard AdBlocker
    link: https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg
  - name: Bitly
    link: https://chrome.google.com/webstore/detail/bitly-powerful-short-link/iabeihobmhlgpkcgjiloemdbofjbdcic
  - name: Bitwarden
    link: https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb
  - name: Falcon
    link: https://chrome.google.com/webstore/detail/falcon/mmifbbohghecjloeklpbinkjpbplfalb
  - name: Floccus
    link: https://chrome.google.com/webstore/detail/floccus-bookmarks-sync/fnaicdffflnofjppbagibeoednhnbjhg
  - name: Git History Browser Extension
    link: https://chrome.google.com/webstore/detail/git-history-browser-exten/laghnmifffncfonaoffcndocllegejnf
  - name: Google Dictionary
    link: https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja
  - name: Grammarly
    link: https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen
  - name: Headless Recorder
    link: https://chrome.google.com/webstore/detail/headless-recorder/djeegiggegleadkkbgopoonhjimgehda
  - name: HTTPS Everywhere
    link: https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp
  - name: JSON Viewer Pro
    link: https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc
  - name: LastPass
    link: https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd
  - name: Markdown Here
    link: https://chrome.google.com/webstore/detail/markdown-here/elifhakcjgalahccnjkneoccemfahfoa
  - name: MetaMask
    link: https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn
  - name: Octohint
    link: https://chrome.google.com/webstore/detail/octohint/hbkpjkfdheainjkkebeoofkpgddnnbpk
  - name: Rakuten
    link: https://chrome.google.com/webstore/detail/rakuten-get-cash-back-for/chhjbpecpncaggjpdakmflnfcopglcmi
  - name: Screenity - Screen Recorder & Annotation Tool
    link: https://chrome.google.com/webstore/detail/screenity-screen-recorder/kbbdabhdfibnancpjfhlkhafgdilcnji
  - name: SingleFile
    link: https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle
  - name: SponsorBlock
    link: https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone
  - name: Vimeo Record
    link: https://chrome.google.com/webstore/detail/vimeo-record-screen-webca/ejfmffkmeigkphomnpabpdabfddeadcb
  - name: Web Vitals
    link: https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en
default_browser: brave

# yamllint disable rule:line-length
go_packages:
  - repo: github.com/camptocamp/bivac
  - repo: github.com/genuinetools/bane # AppArmor profile generator√•
  - repo: github.com/nishanths/license # Source: https://github.com/nishanths/license
  - repo: github.com/rakyll/hey # Load tester
  - repo: github.com/tj/node-prune # node-prune: Removes unnecessary files in node_modules folders
  - repo: github.com/ericchiang/pup # curl -s https://news.ycombinator.com/ | pup 'table table tr:nth-last-of-type(n+2) td.title a' Source: https://github.com/ericchiang/pup
# yamllint enable rule:line-length

homebrew_casks:
  - name: clocker
    when: "{{ ansible_os_family == 'Darwin' }}"
  - name: stats
    when: "{{ ansible_os_family == 'Darwin' }}"

homebrew_packages:
  - name: automake
  - name: carthage
    when: "{{ ansible_os_family == 'Darwin' }}"
  - name: findutils
  - name: ideviceinstaller
  - name: libimobiledevice

nodejs_npm_global_packages:
  - name: "@angular/cli"
  - name: "@cloudflare/wrangler"
  - name: "@ionic/cli"
  - name: "@nestjs/cli"
  - name: "@prettier/plugin-php"
  - name: "@prettier/plugin-ruby"
  - name: "@prettier/plugin-xml"
  - name: "@sentry/cli"
  - name: "@vercel/ncc" # Convert project to a single js file
  - name: add-gitignore
  - name: auto-install
  - name: bitly-cli-client
  - name: caniuse-cmd
  - name: carbon-now-cli
  - name: commitizen
  - name: composerize
  - name: cordova
  - name: deviceframe
  - name: editly
  - name: electron
  - name: emma-cli
  - name: emoj
  - name: empty-trash-cli
  - name: eslint
  - name: firebase-tools
  - name: firetable
  - name: fkill-cli
  - name: fx
  - name: gistup
  - name: git-open
  - name: git-standup
  - name: google-font-installer
  - name: gtop
  - name: gulp
  - name: imgur-uploader-cli # Source: https://github.com/kevva/imgur-uploader-cli
  - name: ios-deploy
    when: "{{ ansible_os_family == 'Darwin' }}" # Quotes and brackets required
  - name: ipfs-deploy
  - name: is-up-cli
  - name: jp-cli
  - name: jsfmt
  - name: localtunnel
  - name: mjml
  - name: mklicense
  - name: movie-cli
  - name: nativefier
  - name: navi
  - name: nectarjs
  - name: newman
  - name: np
  - name: npm-check
  - name: nrm
  - name: oclif
  - name: package-size
  - name: pageres-cli
  - name: pm2
  - name: pxi
    npm: pxi
    github: github.com/Yord/pxi
  - name: pkg # Source: https://github.com/vercel/pkg
  - name: prettier
  - name: prettier-package-json
  - name: prettier-plugin-go-template
  - name: prettier-plugin-java
  - name: prettier-plugin-properties
  - name: prettier-plugin-sh
  - name: prettier-plugin-toml
  - name: psi
  - name: serve # Source: https://github.com/vercel/serve
  - name: serverless
  - name: share-cli # Source: https://github.com/marionebl/share-cli
  - name: sharp-cli
  - name: speed-test # Source: https://github.com/sindresorhus/speed-test
  - name: stegcloak # Allows you to add an encrypted, hidden phrase in any text string (works by using invisible characters)
  - name: surge
  - name: svgo
  - name: taskbook # Command-line to-do list application
  - name: terminalizer # Record terminal as an animated GIF (https://github.com/faressoft/terminalizer)
  - name: tinypng-cli
  - name: tldr
  - name: typescript
  - name: wallace-cli
  - name: wifi-password-cli
  - name: zx

pip_packages:
  - name: ansible-lint # Recommends coding style changes for Ansible
  - name: asciinema
  - name: aws-shell # CLI for AWS CLI that includes auto-completion (https://github.com/awslabs/aws-shell)
  - name: cookiecutter # Boilerplate/templating CLI
  - name: get-port-cli
  - name: gixy # NGINX configuration linter
  - name: httpstat # cURL wrapper that looks pretty and has timing information
  - name: http-prompt # Interactive command-line HTTP client featuring autocomplete and syntax highlighting
  - name: iredis # CLI for Redis which includes auto-completion and syntax highlighting (https://github.com/laixintao/iredis)
  - name: kube-shell # CLI for kubectl that includes auto-completion and syntax highlighting (https://github.com/cloudnativelabs/kube-shell)
  - name: litecli # CLI for SQLite that includes auto-completion and syntax highlighting (https://github.com/dbcli/litecli)
  - name: locust # Web performance benchmarking tool with UI
  - name: netaddr # Used for ipaddr filter on Ansible
  - name: ngxtop # Log information extractor program for NGINX
  - name: molecule # Used for testing Ansible roles
  - name: mycli # CLI for MySQL that includes auto-completion and syntax highlighting (https://github.com/dbcli/mycli)
  - name: pre-commit # Runs tasks before committing changes
  - name: pywhat # Pass it a key/string and it will detect what kind of text/secret it is
  - name: social-analyzer # Find profiles across 900 social networks by username
  - name: spotdl # Downloads music from YouTube and applies meta from Spotify
  - name: truffleHog # Scans git repositories for secrets
  - name: virtualenv # Provides capability to install folder-isolated dependencies
  - name: wpscan # WordPress vulnerability scanner
  - name: yamllint # Lints .yml files

ruby_gems:
  - name: bropages # Community-powered man pages
  - name: bundler # Package management for Ruby gems - Source: https://github.com/rubygems/bundler
  - name: chef # Configuration management software
  - name: cocoapods # Dependency manager for Swift and Objective-C Cocoa projects
  - name: gist
  - name: mdl # Markdown file linter - Source: https://github.com/markdownlint/markdownlint
  - name: t # Twitter CLI

vpn_connections:
  - file: Mullvad OpenVPN Denver (UDP 53).ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN Hong Kong.ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN Italy.ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN NYC.ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad OpenVPN Secaucus (TCP 80).ovpn
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard Germany (Custom Port).nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard Italy Brazil.nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard NYC (Custom Port).nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard NYC.nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: Mullvad WireGuard Switzerland.nmconnection
    password: "{{ mullvad_password }}"
    username: "{{ mullvad_username }}"
  - file: NordVPN OpenVPN Texas.ovpn
    password: "{{ nordvpn_password }}"
    username: "{{ nordvpn_username }}"

vscode_extensions:
  - aaron-bond.better-comments
  - attilabuti.vscode-mjml
  - bierner.markdown-emoji
  - ChakrounAnas.turbo-console-log
  - ChFlick.firecode
  - chrmarti.regex
  - CoenraadS.bracket-pair-colorizer
  - DavidAnson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - dracula-theme.theme-dracula
  - drewbourne.vscode-remark-lint
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - ericadamski.carbon-now-sh
  - firefox-devtools.vscode-firefox-debug
  - formulahendry.auto-rename-tag
  - formulahendry.code-runner
  - foxundermoon.shell-format # Missing from code server
  - GitHub.vscode-pull-request-github
  - GitLab.gitlab-workflow
  - googlecloudtools.cloudcode # Missing from code server
  - golang.Go
  - HashiCorp.terraform
  - IBM.output-colorizer
  - johnpapa.vscode-peacock
  - kruemelkatze.vscode-dashboard
  - mads-hartmann.bash-ide-vscode
  - mechatroner.rainbow-csv
  - msjsdiag.debugger-for-chrome
  - msjsdiag.debugger-for-edge
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-vscode-remote.remote-containers # Missing from code server
  - ms-vscode-remote.remote-ssh # Missing from code server
  - ms-vscode-remote.remote-wsl # Missing from code server
  - ms-python.python
  - ms-vscode.PowerShell
  - ms-vscode.vscode-typescript-tslint-plugin
  - MS-vsliveshare.vsliveshare # Missing from code server
  - MS-vsliveshare.vsliveshare-audio
  - paulvarache.vscode-taskfile
  - philnash.ngrok-for-vscode
  - PKief.material-icon-theme
  - pnp.polacode
  - pranaygp.vscode-css-peek
  - quicktype.quicktype
  - rbbit.typescript-hero
  - redhat.ansible
  - redhat.vscode-yaml # New
  - richie5um2.vscode-sort-json # New
  - Rubymaniac.vscode-paste-and-indent
  - Shan.code-settings-sync
  - shd101wyy.markdown-preview-enhanced
  - softwaredotcom.swdc-vscode
  - steoates.autoimport
  - streetsidesoftware.code-spell-checker # New
  - stylelint.vscode-stylelint
  - TabNine.tabnine-vscode
  - toba.vsfire
  - tusaeff.vscode-iterm2-theme-sync
  - tyriar.sort-lines # New
  - usernamehw.errorlens
  - VisualStudioExptTeam.vscodeintellicode # Missing from code server
  - vsciot-vscode.vscode-arduino
  - vscoss.vscode-ansible
  - vsls-contrib.gistfs
  - WallabyJs.quokka-vscode
  - wayou.vscode-todo-highlight
  - wix.vscode-import-cost
