---
# These are the default VSCode extensions installed on any host in the desktop group.
vscode_extensions:
  # @action VSCode Extensions # [attilabuti.vscode-mjml](https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml)
  # MJML preview, lint, and compile
  - name: attilabuti.vscode-mjml

  # @action VSCode Extensions # [bierner.markdown-emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji)
  # Adds emoji syntax support to VS Code's built-in Markdown preview
  - name: bierner.markdown-emoji

  # @action VSCode Extensions # [ChakrounAnas.turbo-console-log](https://marketplace.visualstudio.com/items?itemName=ChakrounAnas.turbo-console-log)
  # This extension make debugging much easier by automating the operation of writing meaningful log message
  - name: ChakrounAnas.turbo-console-log

  # @action VSCode Extensions # [ChFlick.firecode](https://marketplace.visualstudio.com/items?itemName=ChFlick.firecode)
  # Firestore security rule support for Visual Studio Code
  - name: ChFlick.firecode

  # @action VSCode Extensions # [chrmarti.regex](https://marketplace.visualstudio.com/items?itemName=chrmarti.regex)
  # Shows the current regular expression's matches in a side-by-side document
  - name: chrmarti.regex

  # @action VSCode Extensions # [CoenraadS.bracket-pair-colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)
  # This extension allows matching brackets to be identified with colours
  - name: CoenraadS.bracket-pair-colorizer

  # @action VSCode Extensions # [DavidAnson.vscode-markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
  # Markdown/CommonMark linting and style checking for Visual Studio Code
  - name: DavidAnson.vscode-markdownlint

  # @action VSCode Extensions # [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
  # Integrates ESLint into VS Code
  - name: dbaeumer.vscode-eslint

  # @action VSCode Extensions # [dracula-theme.theme-dracula](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)
  # A dark theme for Visual Studio Code
  - name: dracula-theme.theme-dracula

  # @action VSCode Extensions # [drewbourne.vscode-remark-lint](https://marketplace.visualstudio.com/items?itemName=drewbourne.vscode-remark-lint)
  # Use Unified, Remark, and Retext plugins to lint Markdown
  - name: drewbourne.vscode-remark-lint

  # @action VSCode Extensions # [eamodio.gitlens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
  # GitLens is a popular extension that supercharges the Git capabilities built into VS Code
  - name: eamodio.gitlens

  # @action VSCode Extensions # [EditorConfig.EditorConfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
  # This plugin attempts to override user/workspace settings with setting found in .editorconfig files
  - name: EditorConfig.EditorConfig

  # @action VSCode Extensions # [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
  # Prettier is an opinionated code formatter
  - name: esbenp.prettier-vscode

  # @action VSCode Extensions # [ericadamski.carbon-now-sh](https://marketplace.visualstudio.com/items?itemName=ericadamski.carbon-now-sh)
  # A VS Code extension to open the current editor content in carbon.now.sh
  - name: ericadamski.carbon-now-sh

  # @action VSCode Extensions # [firefox-devtools.vscode-firefox-debug](https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug)
  # A VS Code extension to debug web applications and extensions running in the Mozilla Firefox browser
  - name: firefox-devtools.vscode-firefox-debug

  # @action VSCode Extensions # [formulahendry.auto-rename-tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)
  # Automatically rename paired HTML/XML tag, same as Visual Studio IDE does
  - name: formulahendry.auto-rename-tag

  # @action VSCode Extensions # [formulahendry.code-runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)
  # Run code snippet or code file
  - name: formulahendry.code-runner

  # @action VSCode Extensions # [foxundermoon.shell-format](https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format)
  #
  - name: foxundermoon.shell-format

  # @action VSCode Extensions # [GitHub.vscode-pull-request-github](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)
  # Review and manage your GitHub pull requests and issues directly in VS Code
  - name: GitHub.vscode-pull-request-github

  # @action VSCode Extensions # [GitLab.gitlab-workflow](https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow)
  # This extension integrates GitLab to VS Code
  - name: GitLab.gitlab-workflow

  # @action VSCode Extensions # [GoogleCloudTools.cloudcode](https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode)
  # This extension brings the power and convenience of IDEs to cloud-native application development
  - name: GoogleCloudTools.cloudcode

  # @action VSCode Extensions # [golang.Go](https://marketplace.visualstudio.com/items?itemName=golang.Go)
  # This extension provides rich language support for the Go programming language, integrates with Google Cloud services like Google Kubernetes Engine, Cloud Run, Cloud APIs, and Secret Manager
  - name: golang.Go

  # @action VSCode Extensions # [HashiCorp.terraform](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform)
  # This extension adds syntax highlighting and other editing features for Terraform files using the Terraform Language Server
  - name: HashiCorp.terraform

  # @action VSCode Extensions # [IBM.output-colorizer](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer)
  # This extension adds syntax colorization for both the output/debug/extensions panel and *.log files, other extension that colorize the output panel will disable this extension
  - name: IBM.output-colorizer

  # @action VSCode Extensions # [johnpapa.vscode-peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock)
  # This extension subtly changes the color of the Visual Studio workspace
  - name: johnpapa.vscode-peacock

  # @action VSCode Extensions # [kruemelkatze.vscode-dashboard](https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard)
  # This VS code extension organize the projects in a speed-dial like manner
  - name: kruemelkatze.vscode-dashboard

  # @action VSCode Extensions # [mads-hartmann.bash-ide-vscode](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode)
  # This extension utilizes the bash language server, that is based on Tree Sitter and its grammar for Bash and supports explainshell integration
  - name: mads-hartmann.bash-ide-vscode

  # @action VSCode Extensions # [mechatroner.rainbow-csv](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv)
  # This extension highlights columns in comma, tab, semicolon and pipe - separated files in different colors - provides info about column on hover, transforms and filters tables using built-in SQL-like query language
  - name: mechatroner.rainbow-csv

  # @action VSCode Extensions # [msjsdiag.debugger-for-chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
  # This extension has been deprecated as Visual Studio Code now has a bundled JavaScript Debugger that covers the same functionality
  - name: msjsdiag.debugger-for-chrome

  # @action VSCode Extensions # [msjsdiag.debugger-for-edge](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge)
  # This extension debugs JavaScript code in the Microsoft Edge browser, also used to enable JavaScript debugging inside the Microsoft Edge browser when launched from ASP.Net Projects in Visual Studio
  - name: msjsdiag.debugger-for-edge

  # @action VSCode Extensions # [ms-azuretools.vscode-docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
  # This extension makes it easy to build, manage, and deploy containerized applications from Visual Studio Code
  - name: ms-azuretools.vscode-docker

  # @action VSCode Extensions # [ms-kubernetes-tools.vscode-kubernetes-tools](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools)
  # The extension for developers building applications to run in Kubernetes clusters and for DevOps staff troubleshooting Kubernetes applications
  - name: ms-kubernetes-tools.vscode-kubernetes-tools

  # @action VSCode Extensions # [ms-vscode-remote.remote-containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
  # The Remote - Containers extension enables the use a Docker container as a full-featured development environment
  - name: ms-vscode-remote.remote-containers

  # @action VSCode Extensions # [ms-vscode-remote.remote-ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
  # The Remote - SSH enables the use of any remote machine with a SSH server as the development environment
  - name: ms-vscode-remote.remote-ssh

  # @action VSCode Extensions # [ms-vscode-remote.remote-wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)
  # The Remote - WSL extension enables the use VS Code on Windows to build Linux applications that run on the Windows Subsystem for Linux(WSL)
  - name: ms-vscode-remote.remote-wsl

  # @action VSCode Extensions # [ms-python.python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
  # A VS Code extension with rich support for the Python language, including features such as IntelliSense (Pylance), linting, debugging, code navigation, code formatting, refactoring, variable explorer, test explorer, and more
  - name: ms-python.python

  # @action VSCode Extensions # [ms-vscode.PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell)
  # This extension provides rich PowerShell language support for Visual Studio Code
  - name: ms-vscode.PowerShell

  # @action VSCode Extensions # [ms-vscode.vscode-typescript-tslint-plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin)
  # This extension checks TypeScript code for readability, maintainability, and functionality errors
  - name: ms-vscode.vscode-typescript-tslint-plugin

  # @action VSCode Extensions # [MS-vsliveshare.vsliveshare](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)
  # This extension enables to collaboratively edit and debug with others in real time, regardless what programming languages are used
  - name: MS-vsliveshare.vsliveshare

  # @action VSCode Extensions # [MS-vsliveshare.vsliveshare-audio](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-audio)
  # This extension enhances the existing Visual Studio Live Share experience, by enabling to quickly spin up an audio call directly from within Visual Studio Code, without needing to use a separate tool or service
  - name: MS-vsliveshare.vsliveshare-audio

  # @action VSCode Extensions # [Orta.vscode-jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest)
  # Manage and run Jest tests
  - name: Orta.vscode-jest

  # @action VSCode Extensions # [paulvarache.vscode-taskfile](https://marketplace.visualstudio.com/items?itemName=paulvarache.vscode-taskfile)
  # This extension provides Intellisense, Tasks, a Tree View and Hover actions for your Taskfiles
  - name: paulvarache.vscode-taskfile

  # @action VSCode Extensions # [philnash.ngrok-for-vscode](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode)
  #  A VSCode extension for controlling ngrok from the command palette
  - name: philnash.ngrok-for-vscode

  # @action VSCode Extensions # [PKief.material-icon-theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)
  # Material design icons
  - name: PKief.material-icon-theme

  # @action VSCode Extensions # [pnp.polacode](https://marketplace.visualstudio.com/items?itemName=pnp.polacode)
  # A VSCode extension that creates unique and sharable screenshots of code
  - name: pnp.polacode

  # @action VSCode Extensions # [pranaygp.vscode-css-peek](https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek)
  # A VSCode extension for peeking at CSS definitions from a class or id taq in HTML
  - name: pranaygp.vscode-css-peek

  # @action VSCode Extensions # [quicktype.quicktype](https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype)
  # An extension that generates types and helper code for reading JSON
  - name: quicktype.quicktype

  # @action VSCode Extensions # [rbbit.typescript-hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero)
  # A VSCode extension to organize and sort all the TS imports
  - name: rbbit.typescript-hero

  # @action VSCode Extensions # [redhat.ansible](https://marketplace.visualstudio.com/items?itemName=redhat.ansible)
  # This extension adds language support for Ansible to Visual Studio Code and OpenVSX compatible editors by leveraging ansible-language-server
  - name: redhat.ansible

  # @action VSCode Extensions # [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
  # Provides comprehensive YAML Language support to Visual Studio Code, via the yaml-language-server, with built-in Kubernetes syntax support
  - name: redhat.vscode-yaml

  # @action VSCode Extensions # [richie5um2.vscode-sort-json](https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-sort-json)
  # Alphabetically sorts the keys in selected JSON objects
  - name: richie5um2.vscode-sort-json

  # @action VSCode Extensions # [Rubymaniac.vscode-paste-and-indent](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent)
  # This extension adds limited support for pasting and indenting code
  - name: Rubymaniac.vscode-paste-and-indent

  # @action VSCode Extensions # [Shan.code-settings-sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)
  # This extension enables to share VS Code configurations such as settings, keybindings, and installed extensions across the machine
  - name: Shan.code-settings-sync

  # @action VSCode Extensions # [shd101wyy.markdown-preview-enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)
  # An extension that provides with many useful functionalities such as automatic scroll sync, math typesetting, mermaid, PlantUML, pandoc, PDF export, code chunk, presentation writer, etc
  - name: shd101wyy.markdown-preview-enhanced

  # @action VSCode Extensions # [softwaredotcom.swdc-vscode](https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode)
  # A plugin for automatic programming metrics and time tracking Visual Studio Code
  - name: softwaredotcom.swdc-vscode

  # @action VSCode Extensions # [steoates.autoimport](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport)
  # An extension that automatically finds, parses and provides code actions and code completion for all available imports
  - name: steoates.autoimport

  # @action VSCode Extensions # [streetsidesoftware.code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
  # A basic spell checker that works well with camelCase code
  - name: streetsidesoftware.code-spell-checker

  # @action VSCode Extensions # [stylelint.vscode-stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint)
  # A mighty, modern CSS linter that helps to enforce consistent conventions and avoid errors in stylesheets
  - name: stylelint.vscode-stylelint

  # @action VSCode Extensions # [TabNine.tabnine-vscode](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode)
  # Tabnine is the AI code completion tool trusted by millions of developers to code faster with fewer errors
  - name: TabNine.tabnine-vscode

  # @action VSCode Extensions # [toba.vsfire](https://marketplace.visualstudio.com/items?itemName=toba.vsfire)
  # A VSCode extension for syntax highlighting, hover help and code completions with Firestore security rules and index definition files
  - name: toba.vsfire

  # @action VSCode Extensions # [tusaeff.vscode-iterm2-theme-sync](https://marketplace.visualstudio.com/items?itemName=tusaeff.vscode-iterm2-theme-sync)
  # An extension that synchronizes an iTerm2 color profile with selected VSCode theme
  - name: tusaeff.vscode-iterm2-theme-sync

  # @action VSCode Extensions # [tyriar.sort-lines](https://marketplace.visualstudio.com/items?itemName=tyriar.sort-lines)
  # An extension that sorts lines of text in Visual Studio Code
  - name: tyriar.sort-lines

  # @action VSCode Extensions # [usernamehw.errorlens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)
  # An extension that charges language diagnostic features by making diagnostics stand out more prominently, highlighting the entire line wherever a diagnostic is generated by the language and also prints the message inline
  - name: usernamehw.errorlens

  # @action VSCode Extensions # [VisualStudioExptTeam.vscodeintellicode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)
  # The IntelliCode extension for Visual Studio Code provides artificial intelligence-assisted IntelliSense for Python, Java, TypeScript, and JavaScript
  - name: VisualStudioExptTeam.vscodeintellicode

  # @action VSCode Extensions # [vsciot-vscode.vscode-arduino](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino)
  # The Arduino extension makes it easy to develop, build, deploy and debug your Arduino sketches in Visual Studio Code, with a rich set of functionalities
  - name: vsciot-vscode.vscode-arduino

  # @action VSCode Extensions # [vscoss.vscode-ansible](https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible)
  # A VSCode extension for Ansible
  - name: vscoss.vscode-ansible

  # @action VSCode Extensions # [vsls-contrib.gistfs](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs)
  # A Visual Studio Code extension that allows you to edit GitHub Gists and repositories from the comfort of your favorite editor
  - name: vsls-contrib.gistfs

  # @action VSCode Extensions # [WallabyJs.quokka-vscode](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)
  # An extension for rapid JavaScript / TypeScript prototyping
  - name: WallabyJs.quokka-vscode

  # @action VSCode Extensions # [wayou.vscode-todo-highlight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight)
  # An extension that highlights TODO, FIXME, and other annotations within the code
  - name: wayou.vscode-todo-highlight

  # @action VSCode Extensions # [wix.vscode-import-cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost)
  # This extension will display inline in the editor the size of the imported package
  - name: wix.vscode-import-cost

# Internal note: RegEx replace code:  \n  # @action Ruby Gems # [$1](https://rubygems.org/gems/$1)\n  # \n  - name: $1
