---
roles:
  - name: professormanhattan.homebrew
collections:
  - name: chocolatey.chocolatey
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
