---
- name: "Ensure {{ app_name }} is installed"
  become: false
  homebrew_cask:
    name: android-studio
    state: "{{ app_state | default('present') }}"

# TODO: Check if Android Studio already exists before running the installer
# The installer will report the following message:
# fatal: [workstation]: FAILED! => {"changed": false, "msg": "Updating Homebrew...\n
# Error: It seems there is already an App at '/Applications/Android Studio.app'."}
