---
- name: "Ensure {{ app_name }} is installed"
  chocolatey.chocolatey.win_chocolatey:
    name: androidstudio
    params: /PinnedToTaskbar

- name: "Ensure the {{ app_name }} shortcut is at the top level of the Start Menu"
  include_role:
    name: windows_startmenu
