---
- name: Install role dependencies
  include_role:
    name: "{{ item }}"
  loop: "{{ role_dependencies }}"
  when: install_role_dependencies | default(true)

- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
