---
virtualbox_apt_key: https://www.virtualbox.org/download/oracle_vbox_2016.asc
virtualbox_apt_repository: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
