---
version: '3'

vars:
  REPOSITORY_LIST: .cache/repository-list.txt

tasks:
  group:exec:
    desc: Execute a shell script across all repositories in a group and commit the changes
    summary: |
      # Execute script across entire groups of GitLab repositories

      This task will recursively compile a list of all projects that are in a group and its'
      subgroups and then execute a command in each of the repositories.

      **Example (in the format task taskName -- gitlabGroup ---- commandsToRun):**
      `task {{.TASK}} -- megabyte-labs/ansible-roles ---- 'rm .ansible-lint; git add --all; git commit; git push; etc.'`
    cmds:
      - task: group:exec:{{if .CLI_ARGS}}cli{{else}}prompt{{end}}

  group:exec:cli:
    cmds:
      - task git:gitlab:group:repositories -- {{index (splitList " ---- " .CLI_ARGS) 0}}
      - |
        BASE_PWD="$PWD"
        function execRepo() {
          REPO_DETAILS="$1"
          REPO_URL="$(echo $REPO_DETAILS | sed 's/\s.*$//')"
          REPO_PATH="$(echo $REPO_DETAILS | sed 's/^.*\s//')"
          DIR_NAME="$(dirname $REPO_PATH)"
          mkdir -p "$DIR_NAME"
          if [ -d "$REPO_PATH" ]; then
            cd "$REPO_PATH"
            git reset --hard HEAD
            git clean -fxd
            git pull origin master
            cd "$BASE_PWD"
          else
            git clone --depth=1 "$REPO_URL" "$REPO_PATH"
          fi
          echo "Running bash command on $REPO_PATH"
          (
            cd $REPO_PATH
            {{index (splitList " ---- " .CLI_ARGS) 1}}
            cd $BASE_PWD
          )
          echo "Finished running bash command on $REPO_PATH"
        }
        cat {{.REPOSITORY_LIST}} | while IFS= read -r REPO_DETAILS; do
          echo "Executing logic on $REPO_DETAILS"
          execRepo "$REPO_DETAILS" &
        done
        wait

  group:exec:prompt:
    interactive: true
    cmds:
      - mkdir -p .cache
      - node .config/scripts/prompts/gitlab-group.js

  group:repositories:
    deps:
      - :install:software:glab
      - :install:software:jq
    summary: |
      # Return repositories belonging to group and sub-groups

      Given a GitLab group path (which can include subgroups as well), this task will cycle through
      the group and its' subgroups and generate a list of repositories. The repositories are
      saved to a file located at `{{.REPOSITORY_LIST}}`.

      **Example specifying a group and subgroup:**
      `task {{.TASK}} -- megabyte-labs/ansible-roles`
    cmds:
      - mkdir -p .cache
      - rm -f {{.REPOSITORY_LIST}}
      - task: group:repositories:loop

  group:repositories:loop:
    cmds:
      - glab api "groups/{{urlquery .CLI_ARGS}}" | jq -r '.projects[] | .ssh_url_to_repo + "   " + .path_with_namespace' >> {{.REPOSITORY_LIST}}
      - |
        SUBGROUPS="$(glab api groups/{{urlquery .CLI_ARGS}}/subgroups | jq -r '.[] | .full_path')"
        echo "$SUBGROUPS"
        if [ -n "$SUBGROUPS" ]; then
          echo "$SUBGROUPS" | while IFS= read -r SUBGROUP; do
            task {{.TASK}} -- "$SUBGROUP" &
          done
        fi
        wait
