---
- name: "Add {{ app_name }}'s apt key"
  apt_key:
    url: "{{ azurecli_deb_gpg }}"
    state: present

- name: "Add {{ app_name }}'s apt repository"
  apt_repository:
    filename: "{{ app_name | lower | replace(' ', '-') }}"
    repo: "{{ azurecli_deb_repo }}"
    state: present
    update_cache: true

- name: "Ensure {{ app_name }} is installed"
  apt:
    name: azure-cli
    state: "{{ app_state | default('present') }}"
    update_cache: true
