---
- name: Ensure Java is installed
  dnf:
    name: '{{ java_packages }}'
    state: "{{ app_state | default('present') }}"
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"

- name: Run common Linux tasks
  include_tasks: install-Linux.yml
