---
- name: Ensure 'man' directory exists
  file:
    path: /usr/share/man/man1
    state: directory
    mode: 0644
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 18

- name: Ensure Java is installed
  apt:
    name: '{{ java_packages }}'
    state: present
    update_cache: true
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"

- name: Run common Linux tasks
  include_tasks: install-Linux.yml
