---
# @action Ensures Java is installed
# Ensures the `JAVA_HOME` variable is set
- name: Set JAVA_HOME (if configured)
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined
