---
- name: Include OS-specific variables for Fedora or FreeBSD
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'FreeBSD' or ansible_distribution == 'Fedora'

- name: Include version-specific variables for CentOS/RHEL
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'CentOS' or
    ansible_distribution == 'Red Hat Enterprise Linux' or
    ansible_distribution == 'RedHat'

- name: Include version-specific variables for Ubuntu
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Include version-specific variables for Debian
  include_vars: "{{ ansible_distribution|title }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include version-specific variables for Archlinux and MacOS
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Archlinux' or
    ansible_os_family == 'Darwin'

- name: Include Windows-specific variables
  include_vars: Windows.yml
  when: ansible_os_family == 'Windows'

- name: Define java_packages
  set_fact:
    java_packages: "{{ _java_packages | list }}"
  when: java_packages is not defined

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
