---
homebrew_path: /usr/local/bin/brew # For Darwin/Mac OS X - change this if your Homebrew installation installed brew to another location

# Pass in your own array of extensions to automatically install or
# set vscode_extensions: [] to disable the feature.
vscode_extensions:
  - CoenraadS.bracket-pair-colorizer
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - firefox-devtools.vscode-firefox-debug
  - googlecloudtools.cloudcode # Not available on code server (https://github.com/cdr/code-server)
  - golang.Go
  - IBM.output-colorizer
  - msjsdiag.debugger-for-chrome
  - msjsdiag.debugger-for-edge
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-vscode-remote.remote-containers # Not available on code server
  - ms-vscode-remote.remote-ssh # Not available on code server
  - ms-vscode-remote.remote-wsl # Not available on code server
  - ms-python.python
  - ms-vscode.PowerShell
  - ms-vscode.vscode-typescript-tslint-plugin
  - MS-vsliveshare.vsliveshare # Not available on code server
  - pnp.polacode
  - VisualStudioExptTeam.vscodeintellicode # Not available on code server
  - vscode-icons-team.vscode-icons
  - vsciot-vscode.vscode-arduino
  - vscoss.vscode-ansible

user_configs:
  - username: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    vscode_extensions: "{{ vscode_extensions }}"