---
- name: "Ensure {{ app_name }} is installed"
  become: false
  community.general.homebrew_cask:
    name: raspberry-pi-imager
    state: "{{ app_state | default('present') }}"
    sudo_password: "{{ ansible_password }}"
