---
- name: "Ensure {{ app_name }} is installed"
  chocolatey.chocolatey.win_chocolatey:
    name: multipass
    state: "{{ app_state | default('present') }}"

- name: Set VirtualBox provider if preferred # noqa 503
  ansible.windows.win_command: multipass set local.driver=virtualbox
  when: virt_provider == 'virtualbox'
