---
- name: "Ensure {{ app_name }} is installed"
  become: false
  homebrew_cask:
    name: multipass
    state: "{{ app_state | default('present') }}"

- name: Set VirtualBox provider if preferred # noqa 503
  command: multipass set local.driver=virtualbox
  when: virt_provider == 'virtualbox'
