---
- name: Ensure Megabyte Labs configuration directory exists
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "C:/Users/{{ ansible_user }}/.config"
    - "C:/Users/{{ ansible_user }}/.config/megabytelabs"

- name: "Check if {{ app_name }} has configuration stored in C:/Users/{{ ansible_user }}/.config/megabytelabs/{{ app_name }}"
  ansible.windows.win_stat:
    path: "C:/Users/{{ ansible_user }}/.config/megabytelabs/ffsend"
  register: ffsend_config

- name: "Detect previously installed {{ app_name }} version"
  ansible.windows.win_command: type ffsend
  args:
    chdir: "C:/Users/{{ ansible_user }}/.config/megabytelabs"
  changed_when: false
  register: current_ffsend_version
  when: ffsend_config.stat.exists

- name: "Detect the latest {{ app_name }} version"
  ansible.windows.win_uri:
    url: https://api.github.com/repos/timvisee/ffsend/releases/latest
  register: ffsend_latest_release_tag

- name: "Determine whether or not the latest version of {{ app_name }} is already installed"
  set_fact:
    install_ffsend: "{{ (current_ffsend_version.skipped) or \
      ((not current_ffsend_version.skipped) and (current_ffsend_version.stdout != ffsend_latest_release_tag.json.tag_name | replace('v','')) }}"

- name: "Ensure older version of {{ app_name }} is uninstalled"
  ansible.windows.win_file:
    path: "{{ ffsend_path }}/ffsend.exe"
    state: absent

- name: "Ensure {{ app_name }} is installed"
  ansible.windows.win_get_url:
    url: "{{ 'https://github.com/timvisee/ffsend/releases/download/' + ffsend_latest_release_tag.json.tag_name + \
      '/ffsend-' + ffsend_latest_release_tag.json.tag_name + '-windows-x64-static.exe' }}"
    dest: "{{ ffsend_path }}/ffsend.exe"
  when: install_ffsend

- name: "Ensure {{ app_name }} installation is added to PATH"
  ansible.windows.win_path:
    elements: "{{ ffsend_path }}"
    state: present
  when: install_ffsend

- name: "Save meta information about the version of {{ app_name }} that was installed"
  ansible.windows.win_copy:
    dest: "C:/Users/{{ ansible_user }}/.config/megabytelabs/ffsend"
    content: |
      {{ ffsend_latest_release_tag.json.tag_name  | replace('v','') }}
  when: install_ffsend
