---
ripgrep_rpm_key: https://download.copr.fedorainfracloud.org/results/carlwgeorge/ripgrep/pubkey.gpg
ripgrep_rpm_repository: "https://download.copr.fedorainfracloud.org/results/carlwgeorge/ripgrep/epel-7-$basearch/"
