---
omz_plugins: # Plugins to be configured in zshrc
  - git
  - bundler
  - dotenv
  - osx
  - rake
  - rbenv
  - ruby
  - k
omz_theme: "robbyrussell" # Theme to be configured in zshrc
switch_to_zsh: false # Set this to true to change shell to ZSH

install_antigen_pm: false # Set this to true to install Antigen plugin manager

install_prezto: true
