---
lint:yamllint:
  stage: lint
  image:
    name: megabytelabs/yamllint:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.{yaml,yml}'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - yamllint -c .config/yamllint.yml -s .
