---
- name: "Ensure {{ app_name }} is installed"
  become_method: runas
  become_user: "{{ ansible_user }}"
  chocolatey.chocolatey.win_chocolatey:
    name: bat
    state: "{{ app_state | default('present') }}"
