---
galaxy_info:
  role_name: rust
  author: ProfessorManhattan
  description: Installs Rust on nearly any platform
  company: Megabyte Labs
  issue_tracker_url: https://gitlab.com/megabyte-labs/ansible-roles/rust/-/issues
  license: license (MIT)
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Mac OS X
      versions:
        - all
    - name: Windows
      versions:
        - 10
  galaxy_tags:
    - rust
    - programming
    - language
    - packages
    - modern
dependencies:
  - role: professormanhattan.snapd
    when: ansible_system == 'Linux'
  - role: professormanhattan.homebrew
    when: ansible_os_family == "Darwin"
