---
- name: Ensure PowerShell start script directory exists
  become: true
  become_user: "{{ user }}"
  win_file:
    path: "{{ user_powershell_dir }}"
    state: directory

- name: Copy PowerShell start script
  become: true
  become_user: "{{ user }}"
  win_copy:
    src: Microsoft.PowerShell_profile.ps1
    dest: "{{ user_powershell_dir }}\\Microsoft.PowerShell_profile.ps1"
