---
galaxy_info:
  role_name: homebrew
  namespace: professormanhattan
  author: ProfessorManhattan
  description: Installs Homebrew (a package management system) on macOS and Linux systems
  company: Megabyte Labs
  issue_tracker_url: https://gitlab.com/megabyte-labs/ansible-roles/homebrew/-/issues
  license: license (MIT)
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - ansible
    - automated
    - brew
    - debian
    - doctor
    - fedora
    - homebrew
    - install
    - installdoc
    - installdoctor
    - linux
    - macos
    - mblabs
    - megabytelabs
    - molecule
    - professormanhattan
    - role
    - ubuntu
    - washingtondc
    - windows
dependencies: []
