---
azurecli_deb_gpg: https://packages.microsoft.com/keys/microsoft.asc
azurecli_deb_repo: "deb [arch=amd64] {{ https_repository_prefix }}packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
