---
- name: Ensure configuration settings are applied
  become_user: "{{ user.username }}"
  lineinfile:
    path: ~/.config/kitty/kitty.conf
    create: true
    regex: "*{{ config }}*"
    line: "{{ config }}"
  loop: "{{ kitty_config }}"
  loop_control:
    loop_var: config
