---
- name: Install lxml library
  pip:
    name: lxml
    executable: /usr/local/bin/pip3

- name: Update the Default Browser setting
  include_tasks: plist-Darwin.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
