# https://remmina.org/how-to-install-remmina/#red-hatcentos
- name: Add remmina repo
  copy:
    src: copr-remmina.repo
    dest: "{{ remmina_repo_dest }}"

- name: Install remmina 
  dnf:
    name: 'remmina*'
    state: latest 