---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Windows'

# @action Ensures Redis Desktop Manager is installed
# Installs Redis Desktop Manager on Archlinux, CentOS, Debian, Fedora, macOS and Ubuntu
- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Windows'
