---
# defaults file for ipaclient

ipaclient_force_join: false
ipaclient_mkhomedir: false
ipaclient_kinit_attempts: 5
ipaclient_use_otp: false
ipaclient_allow_repair: false
ipaclient_on_master: false
ipaclient_no_ntp: false
ipaclient_no_dns_lookup: false
ipaclient_ssh_trust_dns: false
ipaclient_no_ssh: false
ipaclient_no_sshd: false
ipaclient_no_sudo: false
ipaclient_no_dns_sshfp: false
ipaclient_force: false
ipaclient_force_ntpd: false
ipaclient_no_nisdomain: false
ipaclient_configure_firefox: false
ipaclient_all_ip_addresses: false
ipasssd_fixed_primary: false
ipasssd_permit: false
ipasssd_enable_dns_updates: false
ipasssd_no_krb5_offline_passwords: false
ipasssd_preserve_sssd: false
ipaclient_request_cert: false

### packages ###
ipaclient_install_packages: true
