---
- name: "Ensure {{ app_name }} is installed"
  become: true
  become_user: "{{ ansible_user }}"
  community.general.homebrew_cask:
    name: virtualbox
    state: present
    sudo_password: "{{ ansible_password }}"

- name: "Ensure {{ app_name }} Extension pack is installed"
  become: true
  become_user: "{{ ansible_user }}"
  community.general.homebrew_cask:
    name: virtualbox-extension-pack
    state: present
    sudo_password: "{{ ansible_password }}"
