---
- name: "Add {{ app_name }}'s yum repository"
  yum_repository:
    baseurl: "{{ virtualbox_rpm_repository }}"
    description: VirtualBox repository
    gpgcheck: true
    gpgkey: "{{ virtualbox_rpm_key }}"
    name: virtualbox

- name: "Ensure {{ app_name }} is installed"
  yum:
    name:
      - "{{ vbox_package_name }}"
      - virtualbox-ext-pack
    state: present
    update_cache: true
