---
- name: "Ensure {{ app_name }} is installed"
  become_method: runas
  become_user: "{{ ansible_user }}"
  chocolatey.chocolatey.win_chocolatey:
    name: virtualbox
    state: present
  register: vbox_installation

- name: "Setup {{ app_name }} Extension pack"
  become_method: runas
  become_user: "{{ ansible_user }}"
  block:
    - name: "Remove {{ app_name }} Extension pack if the source files have changed" # noqa 503
      ansible.windows.win_file:
        path: "C:/Program Files/Oracle/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack/"
        state: absent
    - name: "Find the installed version of {{ app_name }}"
      chocolatey.chocolatey.win_chocolatey_facts:
    - name: "Save the version of {{ app_name }} to a variable"
      set_fact:
        vbox_version: "{{ ansible_chocolatey.packages.virtualbox.version }}"
    - name: "Ensure {{ app_name }} Extension pack installer is downloaded and up-to-date"
      ansible.windows.win_get_url:
        url: "{{ 'https://download.virtualbox.org/virtualbox/' + vbox_version + '/Oracle_VM_VirtualBox_Extension_Pack-' + vbox_version + '.vbox-extpack' }}"
        dest: "C:/Program Files/Oracle/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack.zip"
    - name: "Ensure {{ app_name }} Extension pack is installed"
      community.windows.win_unzip:
        src: "C:/Program Files/Oracle/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack.zip"
        dest: "C:/Program Files/Oracle/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack/"
  when: vbox_installation.changed
  always:
    - name: "Remove {{ app_name }} Extension pack installer"
      become_method: runas
      become_user: "{{ ansible_user }}"
      ansible.windows.win_file:
        path: "C:/Program Files/Oracle/VirtualBox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack.zip"
        state: absent
