---
- name: "Ensure {{ app_name }}'s yum repository is added"
  yum_repository:
    baseurl: "{{ nomad_yum_repo }}"
    description: "{{ app_name }}'s repository"
    gpgcheck: true
    gpgkey: "{{ nomad_gpgkey_url }}"
    name: "{{ app_name | lower | replace(' ', '-') }}"
    repo_gpgcheck: true

- name: "Ensure {{ app_name }} is installed"
  dnf:
    name: nomad
    state: "{{ app_state | default('present') }}"
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"
