---
elastic_agent_32_rpm_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-i686.rpm"
elastic_agent_64_rpm_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-x86_64.rpm"
