---
### basic ###
ipareplica_no_host_dns: false
ipareplica_skip_conncheck: false
ipareplica_hidden_replica: false
### server ###
ipareplica_setup_adtrust: false
ipareplica_setup_ca: false
ipareplica_setup_kra: false
ipareplica_setup_dns: false
ipareplica_no_pkinit: false
ipareplica_no_ui_redirect: false
### client ###
ipaclient_mkhomedir: false
ipaclient_force_join: false
ipaclient_no_ntp: false
# ipaclient_ssh_trust_dns: false
# ipaclient_no_ssh: false
# ipaclient_no_sshd: false
# ipaclient_no_dns_sshfp: false
ipaclient_ssh_trust_dns: false
### certificate system ###
ipareplica_skip_schema_check: false
### dns ###
ipareplica_allow_zone_overlap: false
ipareplica_no_reverse: false
ipareplica_auto_reverse: false
ipareplica_false_forwarders: false
ipareplica_auto_forwarders: false
ipareplica_no_dnssec_validation: false
### ad trust ###
ipareplica_enable_compat: false
### uninstall ###
ipareplica_ignore_topology_disconnect: false
ipareplica_ignore_last_of_role: false
### additional ###
### packages ###
ipareplica_install_packages: true
### firewalld ###
ipareplica_setup_firewalld: true
