---
- name: Add specified users to the libvirt and kvm groups
  become: true
  user:
    name: '{{ user.username }}'
    groups:
      - libvirt
      - kvm
    append: true
  when:
    - user.kvm_admin | default(true)
    - user.username is defined
    - user.username
