---
galaxy_info:
  role_name: nvm
  author: ProfessorManhattan
  description: Installs n on Mac OS X and Linux and installs nvm on Windows
  company: Megabyte Labs
  # issue_tracker_url: https://gitlab.com/ProfessorManhattan/Playbooks/-/issues
  license: license (MIT)

  min_ansible_version: 2.10

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Windows
      versions:
        - 10
    - name: MacOS
      versions:
        - all

  galaxy_tags:
    - nodejs
    - nvm
    - "n"
    - version
    - manager

dependencies:
  - nodejs
