---
- name: "Ensure .bashrc includes {{ app_name }}'s completion"
  become: true
  become_user: '{{ user.username }}'
  lineinfile:
    path: ~/.bashrc
    regex: \"complete -C `which aws_completer` aws\"
    line: 'complete -C `which aws_completer` aws'
  tags:
    - dotfiles
