---
- name: "Ensure {{ app_name }} is installed"
  apt:
    deb: "{{ vagrant_deb_url }}"
    state: "{{ app_state | default('present') }}"

- name: "Ensure {{ app_name }} VMWare desktop plugin's package is installed"
  apt:
    deb: "{{ vagrant_vmware_utility_deb_url }}"
    state: "{{ app_state | default('present') }}"
  when: vagrant_vmware_support

- name: Run generic Linux tasks
  include_tasks: install-Linux.yml
