---
- name: "Add {{ app_name }}'s yum repository"
  yum_repository:
    baseurl: "{{ etcher_rpm_repository }}"
    description: "{{ app_name }}'s repository"
    gpgcheck: true
    gpgkey: "{{ etcher_rpm_key }}"
    name: "{{ app_name | lower | replace(' ', '-') }}"
    repo_gpgcheck: true

- name: "Ensure {{ app_name }} is installed"
  dnf:
    name: balena-etcher-electron
    state: "{{ app_state | default('present') }}"
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"
