---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Google Chrome is installed
# Installs Chromium on Archlinux, CentOS, Debian, Fedora and Ubuntu
# @action Ensures Google Chrome is installed
# Installs Google Chrome on macOS and Windows
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"

# @action Ensures Google Chrome is installed
# Configures Google Chrome as the default Browser if desired
- name: "Set {{ app_name }} as the default browser"
  vars:
    default_browser_chosen: "{{ default_browser }}"
  include_role:
    name: helpers/defaultbrowser
  when:
    - default_browser == 'chrome'
    - ansible_os_family != 'Windows'
