---
- name: 'Ensure {{ homebrew_install_path }} exists'
  file:
    path: '{{ homebrew_install_path }}'
    owner: '{{ homebrew_install_user }}'
    group: '{{ homebrew_install_group }}'
    state: directory
    mode: 0775

- name: Ensure Homebrew is installed
  become_user: '{{ homebrew_install_user }}'
  git:
    repo: '{{ homebrew_repo }}'
    version: master
    dest: '{{ homebrew_install_path }}'
    update: false
    depth: 1

- name: 'Ensure proper permissions and ownership on {{ homebrew_bin_path }}'
  file:
    path: '{{ homebrew_bin_path }}'
    state: directory
    owner: '{{ homebrew_install_user }}'
    group: '{{ homebrew_install_group }}'
    mode: 0775

- name: 'Ensure proper ownership on {{ homebrew_install_path }} subdirs'
  file:
    path: '{{ homebrew_install_path }}'
    state: directory
    owner: '{{ homebrew_install_user }}'
    group: '{{ homebrew_install_group }}'
    mode: 0755

- name: Check if homebrew binary is already in place
  stat:
    path: '{{ homebrew_bin_path }}/brew'
  register: homebrew_binary

- name: Symlink brew to homebrew_bin_path
  file:
    src: '{{ homebrew_install_path }}/bin/brew'
    dest: '{{ homebrew_bin_path }}/brew'
    state: link
  when: not homebrew_binary.stat.exists

- name: Ensure proper homebrew folders are in place
  file:
    path: '{{ homebrew_prefix }}/{{ item }}'
    state: directory
    owner: '{{ homebrew_install_user }}'
    group: '{{ homebrew_install_group }}'
    mode: 0755
  loop: '{{ homebrew_directories }}'
