---
- name: restart apt-cacher-ng
  systemd:
    name: apt-cacher-ng
    state: restarted

- name: clear apt cache
  file:
    state: "{{ item.state }}"
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - state: absent
      path: /var/cache/apt
    - state: directory
      path: /var/cache/apt
    - state: absent
      path: /var/lib/apt/lists
    - state: directory
      path: /var/lib/apt/lists

- name: apt update
  apt:
    update_cache: true
