---
- name: Ensure ClamAV packages are installed
  package:
    name: "{{ clamav_packages }}"
    state: present
  register: clamav_packages_install

- name: Ensure rkhunter package is installed
  package:
    name: rkhunter
    state: present
  when: ansible_os_family != 'RedHat'

- name: Run freshclam after ClamAV packages change
  command: freshclam
  when: clamav_packages_install.changed
  register: freshclam_result
  notify: restart clamav
  failed_when:
    - freshclam_result is failed
    - freshclam_result.stderr.find('locked by another process') != -1
  tags: ["skip_ansible_lint"]

- name: Ensure configuration for ClamAV daemon is updated
  lineinfile:
    path: "{{ clamav_daemon_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line | default('') }}"
    mode: 0644
    state: "{{ item.state | default('present') }}"
  loop: "{{ clamav_daemon_configuration_changes }}"

- name: Ensure ClamAV daemon is running (if configured)
  service:
    enabled: "{{ clamav_daemon_enabled }}"
    name: "{{ clamav_daemon }}"
    state: "{{ clamav_daemon_state }}"

- name: Ensure ClamAV freshclam daemon is running (if configured)
  service:
    enabled: "{{ clamav_freshclam_daemon_enabled }}"
    name: "{{ clamav_freshclam_daemon }}"
    state: "{{ clamav_freshclam_daemon_state }}"

- name: Update rkhunter # noqa 301
  command: rkhunter --update && rkhunter --propupd
