---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Antivirus Software is installed
# Installs Antivirus software on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures Antivirus Software is installed
# Installs ClamAV and Rkhunter on Linux and MacOS Systems
# @action Ensures Antivirus Software is installed
# Configures and updates ClamAV and Rkhunter on Linux and MacOS Systems
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
