---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures software is installed
# Installs software from GitHub Releases
# @action Ensures software is installed
# Installs software from binary releases
# @action Ensures software is installed
# Installs software using GO
# @action Ensures software is installed
# Installs software using Cargo
# @action Ensures software is installed
# Installs software on Linux Systems using Snapcraft
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
