---
- name: "Ensure {{ app_name }} is installed"
  chocolatey.chocolatey.win_chocolatey:
    name: nodejs
    state: present

- name: "Ensure NVM is installed"
  chocolatey.chocolatey.win_chocolatey:
    name: nvm
    state: present
  when: nodejs_install_nvm_windows

- name: "Ensure {{ app_name }}'s folder is removed from start menu"
  include_role:
    name: windows_startmenu

- name: "Ensure NPM packages are installed" # TODO: Make this better by using a module that only reinstalls if the version is not already latest
  win_command: "npm install -g {{ item }}@latest"
  loop: "{{ nodejs_npm_global_packages | default([]) }}"
