---
user_configs: []
# For this role to work, you need to populate the user_configs variable.
# An example is provided below. It will add two mounts at /mnt/digitalocean
# and /mnt/dropbox. It will also create symbolic links that mount to the mounts
# in a newly created ~/Cloud folder. All of the rclone.name's and rclone.provider's
# should be set to unique descriptive strings.
#user_configs:
#  - username: "{{ ansible_user }}"
#    rclone:
#      - name: Digital Ocean
#        provider: digitalocean
#        config: |
#          type = s3
#          env_auth = false
#          access_key_id = YourAccessKeyIDHere
#          secret_access_key = YourSecretAccessKeyHere
#          endpoint = nyc3.digitaloceanspaces.com
#          acl = private
#      - name: Dropbox
#        provider: dropbox
#        config: |
#          type = dropbox
#          token = {"access_token":"YourAccessTokenHere","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
#  - username: root
