---
apps:
  #  - bazarr
  #  - cups
  #  - heimdall
  #  - jackett
  #  - kodi
  #  - lidarr
  #  - nextcloud
  #  - nzbget
  #  - ombi
  #  - organizr
  #  - plex
  #  - radarr
  #  - sonarr
  #  - tautulli
  #  - transmission
  - workstation

git_docker_projects:
  - folder: /srv/htpc
    healthcheck_id: 23cfb4b5-2696-43ac-8cb1-22ce99276760
    name: HTPC
    repo: git@gitlab.com:megabyte-space/docker-compose/htpc.git
  - folder: /srv/nextcloud
    healthcheck_id: 0f8178b2-d243-4c7f-bba2-4c16b75d1de1
    name: NextCloud
    repo: git@gitlab.com:megabyte-space/docker-compose/nextcloud.git
    user: root

host_id: workstation

samba_allowed_hosts: 127.0.0.1 10.14.141. 10.14.14. 10.0.0.
samba_netbios_name: HTPC
samba_printers:
  - id: HPOfficeJetPro
    comment: HP OfficeJet Pro 6978 (in Garage)
    name: HP OfficeJet Pro 6978
samba_shares:
  - id: Media
    comment: Movies, TV Shows, and other read-only multimedia
    follow_symlinks: true
    path: /mnt/htpc
    public: true
  - id: Private
    comment: Authenticated share with read/write capabilities (backed up to OneDrive)
    follow_symlinks: true
    path: "/home/{{ ansible_user | default(lookup('env', 'USER')) }}/Documents"
    public: false
    users: "@sambausers"
    writable: true
  - id: Public
    comment: Public folder provided for file sharing on the LAN
    path: "/home/{{ ansible_user | default(lookup('env', 'USER')) }}/Public"
    public: true
    writable: true
samba_workgroup: MEGAGROUP
samba_users:
  - name: "{{ samba_protected_share_name }}"
    password: "{{ samba_protected_share_password }}"
    samba_password: "{{ samba_protected_share_samba_password }}"
    uid: "449"
    groups:
      - sambausers
      - lpadmin
# vpn_routes:
#   - mask: 255.255.255.0
#     next_hop: 10.14.14.1
#     prefix: 10.14.24.0/24
#   - mask: 255.255.255.0
#     next_hop: 10.14.14.1
#     prefix: 10.14.14.0/24
