---
gcloud_deb_gpg: https://packages.cloud.google.com/apt/doc/apt-key.gpg
gcloud_deb_repo: "deb [signed-by=/usr/share/keyrings/googlecloudsdk.gpg] {{ https_repository_prefix }}packages.cloud.google.com/apt cloud-sdk main"

# List of optional components to install
# Add the values from APT Package column in https://cloud.google.com/sdk/docs/components#external_package_managers to the below list
optional_components: []
#  - google-cloud-sdk-app-engine-python
#  - google-cloud-sdk-app-engine-python-extras
#  - google-cloud-sdk-app-engine-java
#  - google-cloud-sdk-app-engine-go
#  - google-cloud-sdk-bigtable-emulator
#  - google-cloud-sdk-cbt
#  - google-cloud-sdk-cloud-build-local
#  - google-cloud-sdk-datalab
#  - google-cloud-sdk-datastore-emulator
#  - google-cloud-sdk-firestore-emulator
#  - google-cloud-sdk-pubsub-emulator
#  - kubectl
