---
- hosts: all
  roles:
    - ../roles/applications/tabby
      when: "'tabby' in install_roles"
    - ../roles/applications/hyper
      when: "'hyper' in install_roles"
    - ../roles/applications/kitty
      when: "'kitty' in install_roles"
