---
# @action Ensures ZSH is configured
# Installs Oh My ZSH on macOS/Linux
# @action Ensures ZSH is configured
# Installs Antigen PM if configured, on macOS/Linux
# @action Ensures ZSH is configured
# Installs `prezto` if configured, on macOS/Linux
# @action Ensures ZSH is configured
# Configures ZSH plugins and themes
- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Windows'
