---
galaxy_info:
  role_name: loop
  author: ProfessorManhattan
  description: Installs Loop (the missing UNIX loop command) on Linux and macOS
  company: Megabyte Labs
  issue_tracker_url: https://gitlab.com/megabyte-labs/ansible-roles/loop/-/issues
  license: license (MIT)

  min_ansible_version: 2.10

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: MacOS
      versions:
        - all

  galaxy_tags:
    - loop
    - shell
    - tools
    - bash

dependencies:
  - role: professormanhattan.snapd
    when: ansible_system == 'Linux'
