---
- name: "Ensure {{ app_name }}'s dependencies are installed"
  community.general.homebrew:
    name: "{{ beets_dependencies }}"
    state: "{{ app_state | default('present') }}"

- name: "Ensure {{ app_name }} is installed"
  pip:
    name: beets
    state: "{{ beets_version | default('latest') }}"
