---
# yamllint disable rule:line-length
dotnet_tools:
  # @dotnet [attacksurfaceanalyzer](https://github.com/microsoft/AttackSurfaceAnalyzer) - Attack Surface Analyzer can help you analyze your operating system's security configuration for changes during software installation
  - name: Microsoft.CST.AttackSurfaceAnalyzer.CLI
