---
- name: "Determine if the {{ extension }} extension is already present"
  become: true
  become_user: "{{ user.username }}"
  command: ls
  args:
    chdir: ~/.vscode/extensions
  register: extension_ls
  changed_when: false

- name: "Install the {{ extension }} extension"
  become: true
  become_user: "{{ user.username }}"
  command: "{{ code_binary_path }} --install-extension {{ extension }}"
  when: not ((extension_ls.stdout | lower) | regex_findall((extension | lower) + '-[0-9]+\.[0-9]+\.[0-9]+') | length)
