---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"

- name: "Install missing {{ app_name }} extensions"
  include_tasks: user.yml
  loop: "{{ user_configs | default([]) }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
  when: (user.system is not defined) or ((user.system is defined) and (not user.system))
