- name: Add Microsoft key 
  rpm_key:
    key: "{{ MS_Key }}"

- name: Add VSCode repo 
  copy:
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: "{{ vscode_repo }}"

- name: Install VSCode 
  dnf:
    name: "{{ vscode }}"
    state: latest