---
lint:black:
  stage: lint
  image:
    name: megabytelabs/black:slim
    entrypoint: ['']
  rules:
    - if: $DO_CI == 'false'
      when: never
    - if: $CI_COMMIT_BRANCH == 'synchronize'
      when: never
    - exists:
        - '**/*.py'
  variables:
    GIT_DEPTH: 1
  script:
    - set -eo pipefail
    - black . --check
