---
- name: restart clamav
  service:
    name: "{{ clamav_daemon }}"
    state: restarted
  when: clamav_daemon_state != 'stopped'

- name: reload clamav
  systemd:
    daemon_reload: true
    name: "{{ clamav_freshclam_daemon }}"
    state: stopped
