---
molecule:
  stage: test
  image: docker:stable-dind
  services:
    - docker:dind
  before_script:
    - apk update && apk add --no-cache
        python3 python3-dev py3-pip gcc git curl build-base
        autoconf automake py3-cryptography linux-headers
        musl-dev libffi-dev openssl-dev openssh
    - docker info
    - python3 --version
    - python3 -m pip install ansible molecule[docker]
    - ansible --version
    - molecule --version
  script:
    - roles/ufw && molecule test
  rules:
    - changes:
        - roles/ufw/*
      when: manual
      allow_failure: true
