---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
- name: Allow DNS traffic (TCP port 53)
  ufw:
    rule: allow
    port: '53'
    proto: tcp
    src: "{{ item }}"
    comment: Allow local DNS lookups (TCP)
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
- name: Allow DNS traffic (UDP port 53)
  ufw:
    rule: allow
    port: '53'
    proto: udp
    src: "{{ item }}"
    comment: Allow local DNS lookups (UDP)
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
- name: Allow all access to TCP port 80 from local networks
  ufw:
    rule: allow
    port: '80'
    proto: tcp
    src: "{{ item }}"
    comment: Allow HTTP from local networks
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16